(() => {
'use strict';
const W=window.Washi=window.Washi||{},T=W.Templates,E=W.Editor,DB=W.DB,X=W.Export;
if(!T||!E||!DB||!X)return;
const $=(s,r=document)=>r.querySelector(s),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),clone=v=>structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v));
const CAT='Seamless Carousel',SW=1080,SH=1350,ADDED='2026-08-14T12:20:00+08:00';
const id=p=>DB.uid(p),base=(type,x,y,w,h,e={})=>({id:id('obj'),type,x,y,w,h,rotation:0,opacity:1,visible:true,locked:false,...e});
const ph=(x,y,w,h,e={})=>base('placeholder',x,y,w,h,{label:'Add photo',fit:'cover',radius:16,...e});
const sh=(x,y,w,h,fill,e={})=>base('shape',x,y,w,h,{shape:'rect',fill,border:'transparent',borderWidth:0,radius:e.radius||0,...e});
const tx=(v,x,y,w,h,s=56,c='#222',e={})=>base('text',x,y,w,h,{text:v,fontSize:s,color:c,font:e.font||'Georgia, serif',align:e.align||'left',bold:!!e.bold,italic:!!e.italic,lineHeight:e.lineHeight||1.02,letterSpacing:e.letterSpacing||0,effect:e.effect||'none',...e});
const st=(v,x,y,s=80,e={})=>base('sticker',x,y,s,s,{content:v,fontSize:s*.8,color:e.color||'#222',...e});
const paper=(x,y,w,h,r=0)=>[sh(x-18,y-18,w+36,h+68,'#fffaf4',{rotation:r,radius:3}),ph(x,y,w,h,{rotation:r,radius:1})];
const tape=(x,y,w,c='#d7bda3',r=-6)=>sh(x,y,w,28,c,{rotation:r,radius:2,opacity:.78});
function tpl(id,title,n,bg,objects,tags=[]){return{id,title,category:CAT,format:'portrait',collection:'Carousel Studio',tags:['carousel','seamless','continuous','instagram','editable',...tags],addedAt:ADDED,bg:{type:'solid',value:bg},objects,carousel:{enabled:true,slideCount:n,slideWidth:SW,slideHeight:SH,durations:Array(n).fill(3),activeSlide:0,view:'slide'}}}
const families={
 panorama:n=>[ph(0,0,SW*n,SH,{radius:0}),tx('one view · keep swiping',70,70,750,70,42,'#fff',{bold:true,effect:'shadow'})],
 scrapbook:n=>Array.from({length:n+2},(_,i)=>{const x=90+i*(SW-180),y=i%2?330:140;return[...paper(x,y,720,830,i%2?5:-4),tape(x+520,y-25,190,i%3===0?'#d8b8c7':'#c5d0bb',i%2?-7:8)]}).flat().concat(tx('little pieces',SW+80,80,560,70,46,'#5a4c45',{italic:true})),
 polaroid:n=>Array.from({length:n*2},(_,i)=>{const x=80+i*(SW/2),y=i%2?430:150;return paper(x,y,510,650,i%2?5:-5)}).flat(),
 film:n=>[sh(0,0,SW*n,SH,'#111'),...Array.from({length:n*2},(_,i)=>ph(40+i*SW/2,150,SW/2-70,1020,{radius:0})),tx('WASHI 400',50,50,340,45,25,'#f0a02a',{font:'Courier New, monospace',bold:true})],
 editorial:n=>[ph(560,0,SW*n-560,SH,{radius:0}),sh(0,0,560,SH,'#f4f0e8'),tx('L\nA\nT\nE\nL\nY',90,80,340,1140,138,'#191919',{bold:true,lineHeight:.88})],
 ripped:n=>[ph(0,0,SW*n,SH,{radius:0}),sh(0,390,SW*n,210,'#faf8f3',{rotation:-2}),sh(0,790,SW*n,160,'#faf8f3',{rotation:2}),tx('one story / many frames',110,560,760,80,48,'#222',{italic:true})],
 travel:n=>[ph(0,0,SW*n,SH,{radius:0,opacity:.45}),sh(150,150,SW*(n-.7),960,'#f8f0e4',{rotation:-3}),ph(230,220,SW*(n-.9),810,{rotation:-3,radius:0}),sh(SW*(n-1.35),90,470,240,'#e7d5cd',{rotation:4}),tx('my travel diaries',SW*(n-1.28),145,360,65,40,'#333',{italic:true}),st('📎',SW*(n-1.0),70,76)],
 grid:n=>Array.from({length:n*6},(_,i)=>{const col=i%(n*2),row=Math.floor(i/(n*2)),w=SW/2-40;return ph(25+col*(SW/2),70+row*410,w,360,{radius:0})}).concat(tx('CONTACT / 001',45,SH-60,350,40,23,'#222',{font:'Courier New, monospace',bold:true})),
 minimal:n=>[ph(360,130,SW*(n-.65),980,{radius:0}),...Array.from({length:n-1},(_,i)=>sh((i+1)*SW-1,0,2,SH,'#222')),tx('quiet frames',65,75,360,55,32,'#222',{italic:true})],
 bold:n=>[...Array.from({length:n},(_,i)=>sh(i*SW,0,SW,SH,['#e96d50','#f5d56a','#6b9d91','#5277a9','#8c6cab'][i%5])),ph(360,190,SW*(n-.7),930,{radius:28}),tx('COLOR',70,65,400,70,58,'#fff',{bold:true})],
 botanical:n=>Array.from({length:n},(_,i)=>ph(i*SW+150,170+(i%2)*70,780,930,{radius:2})).concat(st('🌿',SW-90,55,110),st('🌸',SW*2-110,1040,110),tx('notes from outside',SW+65,1140,620,60,38,'#4f5d49',{italic:true})),
 magazine:n=>[ph(0,0,SW*Math.max(1.8,n-1.4),SH,{radius:0}),sh(SW*Math.max(1.8,n-1.4),0,SW*1.4,SH,'#f5f1e9'),tx('THE\nWEEKEND\nEDIT',SW*(n-1.25),130,850,390,102,'#191919',{bold:true,lineHeight:.92})]
};
const specs=[['panorama','Panorama Clean',3,'#f3f0ea'],['panorama','Panorama Wide',4,'#101010'],['scrapbook','Scrapbook Flow',4,'#eee5d8'],['scrapbook','Paper Trail',3,'#e4ecdf'],['polaroid','Polaroid Chain',4,'#faf8f2'],['polaroid','Instant Memories',5,'#e8dfd1'],['film','Film Strip Journey',5,'#111'],['film','Night Film',3,'#080808'],['editorial','Editorial Swipe',3,'#f4f0e8'],['editorial','Magazine Type Flow',4,'#f1eee7'],['ripped','Ripped Paper Story',3,'#faf8f3'],['ripped','Torn Travel Flow',4,'#e8e1d8'],['travel','Travel Diary Spread',4,'#dce8e4'],['travel','Postcard Journey',5,'#e7ddcc'],['grid','Contact Sheet',3,'#f4f0e8'],['grid','Camera Roll Grid',4,'#fff'],['minimal','Quiet Lines',4,'#f8f7f3'],['minimal','Gallery Walk',3,'#f0efeb'],['bold','Color Block Flow',4,'#e96d50'],['bold','Pop Swipe',3,'#6b9d91'],['botanical','Botanical Notes',3,'#f5f0e6'],['botanical','Garden Diary',4,'#eef1df'],['magazine','Magazine Spread',4,'#f5f1e9'],['magazine','Fashion Editorial',3,'#f2eee7']];
const BUILT=specs.map(([f,n,c,b],i)=>tpl(`carousel-${f}-${i+1}`,`${n} · ${c} Slides`,c,b,families[f](c),[f,n.toLowerCase()]));
const seen=new Set(T.TEMPLATES.map(t=>t.id));for(const t of BUILT)if(!seen.has(t.id))T.TEMPLATES.unshift(t);if(!T.CATEGORIES.includes(CAT))T.CATEGORIES.unshift(CAT);T.TEMPLATE_COUNT=T.TEMPLATES.length;
const original=T.fromTemplate.bind(T);T.fromTemplate=function(templateId){const source=T.TEMPLATES.find(t=>t.id===templateId),p=original(templateId);if(!p||!source?.carousel)return p;const c=clone(source.carousel);c.slideCount=clamp(c.slideCount,2,10);c.durations=Array.from({length:c.slideCount},(_,i)=>Number(c.durations?.[i])||3);c.activeSlide=0;c.view='slide';p.carousel=c;p.width=c.slideWidth*c.slideCount;p.height=c.slideHeight;p.format='portrait';return p};
function p(){return E.getProject?.()||E.state?.project}const active=()=>!!p()?.carousel?.enabled;
function toast(v){const t=$('#toast');if(!t)return;t.textContent=v;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function seams(){let s=$('#washiCarouselSeams');if(!s){s=document.createElement('div');s.id='washiCarouselSeams';s.className='wc-seams';$('#designStage')?.append(s)}const q=p();if(!s)return;if(!active()){s.hidden=true;s.innerHTML='';return}s.hidden=false;s.innerHTML=Array.from({length:q.carousel.slideCount-1},(_,i)=>`<i style="left:${(i+1)*q.carousel.slideWidth}px"></i>`).join('')}
function hud(){let h=$('#washiCarouselHUD');if(h)return h;h=document.createElement('div');h.id='washiCarouselHUD';h.className='wc-hud';h.hidden=true;h.innerHTML='<button data-c="prev">‹</button><strong data-c-label>1 / 3</strong><button data-c="next">›</button><button data-c="view">Strip</button><label>Time <input data-c-time type="number" min=".5" max="60" step=".5" value="3">s</label>';$('#editorView')?.append(h);return h}
function sync(){seams();const h=hud(),q=p();if(!active()){h.hidden=true;return}h.hidden=false;h.querySelector('[data-c-label]').textContent=`${q.carousel.activeSlide+1} / ${q.carousel.slideCount}`;h.querySelector('[data-c="view"]').textContent=q.carousel.view==='slide'?'Strip':'Slide';h.querySelector('[data-c-time]').value=q.carousel.durations[q.carousel.activeSlide]||3;const z=$('#projectSize');if(z)z.textContent=`${q.carousel.slideCount} slides · 1080 × 1350`}
function focus(smooth=false){const q=p(),w=$('#editorWorkspace'),sc=$('#stageScroll');if(!active()||!w||!sc)return;const z=Math.min((w.clientWidth-42)/q.carousel.slideWidth,(w.clientHeight-175)/q.carousel.slideHeight,1);E.setZoom(z);sc.style.placeItems='center start';requestAnimationFrame(()=>sc.scrollTo({left:q.carousel.activeSlide*q.carousel.slideWidth*z,behavior:smooth?'smooth':'auto'}))}
function go(i){const q=p();if(!active())return;q.carousel.activeSlide=clamp(i,0,q.carousel.slideCount-1);sync();if(q.carousel.view==='slide')focus(true);E.save?.({history:false,renderUI:false})}
hud().addEventListener('click',e=>{const a=e.target.closest('[data-c]')?.dataset.c,q=p();if(!a||!active())return;if(a==='prev')go(q.carousel.activeSlide-1);if(a==='next')go(q.carousel.activeSlide+1);if(a==='view'){q.carousel.view=q.carousel.view==='slide'?'strip':'slide';if(q.carousel.view==='slide')focus();else{$('#stageScroll').style.placeItems='center';E.fit()}sync();E.save?.({history:false,renderUI:false})}});hud().addEventListener('change',e=>{if(!e.target.matches('[data-c-time]')||!active())return;const q=p();q.carousel.durations[q.carousel.activeSlide]=clamp(Number(e.target.value)||3,.5,60);E.save?.({history:false,renderUI:false})});
window.addEventListener('washi:selection-changed',()=>requestAnimationFrame(sync));window.addEventListener('washi:project-saved',()=>$('#editorView')?.classList.contains('active')&&requestAnimationFrame(sync));window.addEventListener('resize',()=>active()&&p().carousel.view==='slide'&&focus(),{passive:true});setTimeout(sync,100);
function cut(full,i,c){const o=document.createElement('canvas');o.width=c.slideWidth;o.height=c.slideHeight;o.getContext('2d',{alpha:false}).drawImage(full,i*c.slideWidth,0,c.slideWidth,c.slideHeight,0,0,c.slideWidth,c.slideHeight);return o}const blob=(c,t,q=.94)=>new Promise(r=>c.toBlob(r,t,q));const safe=v=>(String(v||'washi-carousel').replace(/[^\w\- ]+/g,'').trim().replace(/\s+/g,'-')||'washi-carousel').toLowerCase();
async function images(q,fmt='jpg'){const full=await X.renderProject(q),type=fmt==='png'?'image/png':'image/jpeg',ext=fmt==='png'?'png':'jpg',out=[];for(let i=0;i<q.carousel.slideCount;i++){const b=await blob(cut(full,i,q.carousel),type);out.push(new File([b],`${safe(q.name)}-${String(i+1).padStart(2,'0')}.${ext}`,{type}))}return out}
function mime(){if(!window.MediaRecorder)return null;for(const m of['video/mp4','video/webm;codecs=vp9','video/webm'])try{if(!MediaRecorder.isTypeSupported||MediaRecorder.isTypeSupported(m))return m}catch{}return null}
async function video(canvas,seconds,name,i){const type=mime();if(!type||!canvas.captureStream)throw Error('Timed video export is not supported by this browser');const snapshot=document.createElement('canvas');snapshot.width=canvas.width;snapshot.height=canvas.height;snapshot.getContext('2d').drawImage(canvas,0,0);const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),chunks=[],r=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:6000000});r.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise((res,rej)=>{r.onstop=res;r.onerror=()=>rej(r.error)});r.start(250);const start=performance.now(),ms=clamp(seconds,.5,60)*1000;await new Promise(res=>{function f(t){const k=Math.min(1,(t-start)/ms),s=1+.018*k,dx=canvas.width*(s-1)/2,dy=canvas.height*(s-1)/2;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-dx,-dy);ctx.scale(s,s);ctx.drawImage(snapshot,0,0);ctx.restore();t-start<ms?requestAnimationFrame(f):res()}requestAnimationFrame(f)});r.stop();await done;stream.getTracks().forEach(x=>x.stop());const ext=type.includes('mp4')?'mp4':'webm';return new File([new Blob(chunks,{type})],`${safe(name)}-${String(i+1).padStart(2,'0')}.${ext}`,{type})}
async function videos(q){const full=await X.renderProject(q),out=[];for(let i=0;i<q.carousel.slideCount;i++){toast(`Rendering video ${i+1}/${q.carousel.slideCount}`);out.push(await video(cut(full,i,q.carousel),q.carousel.durations[i]||3,q.name,i))}return out}
async function deliver(files,title){if(navigator.share&&navigator.canShare?.({files}))return navigator.share({files,title});const d=$('#wcDownloads');d.hidden=false;d.innerHTML=files.map((f,i)=>{const u=URL.createObjectURL(f);setTimeout(()=>URL.revokeObjectURL(u),120000);return`<a href="${u}" download="${f.name}">${i+1}. ${f.name}</a>`}).join('')}
function sheet(){let s=$('#wcExport');if(s)return s;s=document.createElement('div');s.id='wcExport';s.className='wc-export';s.hidden=true;s.innerHTML='<div class="wc-back" data-close></div><div class="wc-card"><div class="wc-title"><div><small>Seamless Carousel</small><h3>Export</h3></div><button data-close>×</button></div><p>Export numbered slides in Instagram order or turn each slide into a timed motion video.</p><div class="wc-actions"><button data-x="jpg">JPG slides</button><button data-x="png">PNG slides</button><button data-x="video" class="primary">Timed videos</button></div><div id="wcDownloads" hidden></div><small class="note">Video timing uses each slide’s Time setting. This first motion export animates the finished slide; live embedded-video compositing is the next renderer upgrade.</small></div>';document.body.append(s);return s}
function show(){sheet().hidden=false;$('#wcDownloads').hidden=true;$('#wcDownloads').innerHTML=''}sheet().addEventListener('click',async e=>{if(e.target.closest('[data-close]')){sheet().hidden=true;return}const x=e.target.closest('[data-x]')?.dataset.x;if(!x||!active())return;const bs=[...sheet().querySelectorAll('[data-x]')];bs.forEach(b=>b.disabled=true);try{const f=x==='video'?await videos(p()):await images(p(),x);await deliver(f,p().name);toast(`${f.length} files ready`)}catch(err){toast(err?.message||'Export failed')}finally{bs.forEach(b=>b.disabled=false)}});$('#exportButton')?.addEventListener('click',e=>{if(!active())return;e.preventDefault();e.stopImmediatePropagation();show()},true);
const css=document.createElement('style');css.textContent='.wc-seams{position:absolute;inset:0;z-index:26;pointer-events:none}.wc-seams[hidden]{display:none}.wc-seams i{position:absolute;top:0;bottom:0;border-left:3px dashed rgba(220,82,126,.5)}.wc-hud{position:absolute;z-index:45;top:calc(72px + var(--safe-top));left:50%;transform:translateX(-50%);display:flex;gap:6px;align-items:center;padding:6px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.96);box-shadow:var(--shadow-soft)}.wc-hud[hidden]{display:none}.wc-hud button{height:34px;border:0;border-radius:10px;background:var(--pink-50);padding:0 11px;font-weight:850}.wc-hud strong{min-width:60px;text-align:center;font-size:.72rem}.wc-hud label{font-size:.65rem;color:var(--muted);white-space:nowrap}.wc-hud input{width:48px;height:30px;border:1px solid var(--line);border-radius:9px;text-align:center}.wc-export{position:fixed;inset:0;z-index:120}.wc-export[hidden]{display:none}.wc-back{position:absolute;inset:0;background:rgba(30,20,25,.45);backdrop-filter:blur(6px)}.wc-card{position:absolute;left:12px;right:12px;bottom:calc(12px + var(--safe-bottom));max-height:75dvh;overflow:auto;border:1px solid var(--line);border-radius:24px;padding:18px;background:#fffafd;box-shadow:0 24px 70px rgba(40,20,30,.24)}.wc-title{display:flex;justify-content:space-between}.wc-title h3{margin:4px 0}.wc-title small{color:var(--rose);text-transform:uppercase;font-weight:850}.wc-title button{width:38px;height:38px;border:1px solid var(--line);border-radius:12px;background:#fff}.wc-actions{display:grid;gap:8px}.wc-actions button{min-height:48px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:850}.wc-actions .primary{background:var(--rose);color:#fff}.wc-actions button:disabled{opacity:.45}#wcDownloads{display:grid;gap:7px;margin-top:12px}#wcDownloads[hidden]{display:none}#wcDownloads a{padding:11px;border:1px solid var(--line);border-radius:12px;color:var(--ink);text-decoration:none}.wc-card .note{display:block;margin-top:12px;color:var(--muted);line-height:1.4}@media(max-width:430px){.wc-hud{left:10px;right:10px;transform:none;overflow-x:auto}}';document.head.append(css);
W.Carousel={templates:BUILT,images,videos,show,version:'2026.08.14-carousel-1'};
})();
