(() => {
'use strict';
const W=window.Washi=window.Washi||{},DB=W.DB,T=W.Templates,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const state={project:null,selectedId:null,zoom:1,history:[],historyIndex:-1,pointers:new Map(),interaction:null,raf:0,draw:{enabled:false,brush:'pen',color:'#c84f77',width:10,opacity:1,active:null}},el={};
const ids=['designStage','stageFrame','editorWorkspace','objectsLayer','drawingLayer','gridOverlay','safeZoneOverlay','alignmentGuides','selectionBar','projectTitle','projectSize','zoomLabel','undoButton','redoButton'];
function cache(){ids.forEach(id=>el[id]=document.getElementById(id))}
const getProject=()=>state.project,selected=()=>state.project?.objects?.find(o=>o.id===state.selectedId)||null;
function objectLabel(o){if(!o)return'';if(o.maskText)return`Photo letters · ${o.maskText}`;if(o.type==='text')return(o.text||'Text').replace(/\s+/g,' ').slice(0,32);if(o.type==='sticker')return`Sticker ${o.content||''}`;if(o.type==='shape')return'Shape';if(o.type==='video')return'Video';if(o.type==='image')return'Photo';return o.type==='placeholder'?'Photo placeholder':'Layer'}
function setProject(p){state.project=DB.clone(p);state.selectedId=null;state.history=[DB.clone(state.project)];state.historyIndex=0;state.draw.enabled=false;render();requestAnimationFrame(fit)}
function openProject(id){const p=DB.getProject(id);if(!p)return false;setProject(p);return true}
function createProject(format='story',name){const p=T.newProject(format,name);DB.upsertProject(p);setProject(p);return p}
function createFromTemplate(id){const p=T.fromTemplate(id);if(!p)return null;DB.upsertProject(p);setProject(p);return p}
function save({history=true,renderUI=true}={}){if(!state.project)return;DB.upsertProject(state.project);if(history){const snap=DB.clone(state.project),prev=state.history[state.historyIndex];if(!prev||JSON.stringify(prev)!==JSON.stringify(snap)){state.history=state.history.slice(0,state.historyIndex+1);state.history.push(snap);if(state.history.length>35)state.history.shift();state.historyIndex=state.history.length-1}}undoUI();if(renderUI)window.dispatchEvent(new CustomEvent('washi:project-saved',{detail:{id:state.project.id}}))}
function undoUI(){if(el.undoButton)el.undoButton.disabled=state.historyIndex<=0;if(el.redoButton)el.redoButton.disabled=state.historyIndex>=state.history.length-1}
function undo(){if(state.historyIndex<=0)return;state.project=DB.clone(state.history[--state.historyIndex]);DB.upsertProject(state.project);render()}
function redo(){if(state.historyIndex>=state.history.length-1)return;state.project=DB.clone(state.history[++state.historyIndex]);DB.upsertProject(state.project);render()}
function setZoom(z){state.zoom=clamp(z,.06,1.6);stageSize()}
function fit(){if(!state.project||!el.editorWorkspace)return;setZoom(Math.min((el.editorWorkspace.clientWidth-56)/state.project.width,(el.editorWorkspace.clientHeight-150)/state.project.height,1))}
function stageSize(){const p=state.project;if(!p||!el.designStage)return;el.stageFrame.style.width=`${p.width*state.zoom}px`;el.stageFrame.style.height=`${p.height*state.zoom}px`;el.designStage.style.width=`${p.width}px`;el.designStage.style.height=`${p.height}px`;el.designStage.style.transform=`scale(${state.zoom})`;if(el.zoomLabel)el.zoomLabel.textContent=`${Math.round(state.zoom*100)}%`}
function setBackground(){const p=state.project,s=el.designStage,b=p.bg||{type:'solid',value:'#fff'};s.style.background=s.style.backgroundColor=s.style.backgroundImage=s.style.backgroundSize='';if(b.type==='solid')s.style.backgroundColor=b.value;else if(b.type==='gradient')s.style.background=b.value;else{s.style.backgroundColor=b.color||'#fffaf5';if(b.value==='notebook')s.style.backgroundImage='repeating-linear-gradient(0deg,transparent 0 61px,rgba(190,130,154,.17) 62px 64px)';if(b.value==='dots'){s.style.backgroundImage='radial-gradient(rgba(195,79,119,.20) 2px,transparent 2px)';s.style.backgroundSize='34px 34px'}if(b.value==='grid'){s.style.backgroundImage='linear-gradient(rgba(195,79,119,.12) 2px,transparent 2px),linear-gradient(90deg,rgba(195,79,119,.12) 2px,transparent 2px)';s.style.backgroundSize='60px 60px'}}}
function filterCSS(o){const p={none:'none',soft:'brightness(1.05) saturate(.9) contrast(.96)',film:'contrast(1.08) saturate(.82) sepia(.12)',digicam:'contrast(1.12) saturate(1.18)',bw:'grayscale(1) contrast(1.08)',warm:'sepia(.14) saturate(1.05) brightness(1.03)',fade:'contrast(.88) saturate(.8) brightness(1.08)'};return o.filterPreset&&o.filterPreset!=='custom'?(p[o.filterPreset]||'none'):`brightness(${o.brightness??1}) contrast(${o.contrast??1}) saturate(${o.saturation??1})`}
function maskLayout(w,h){const size=Math.min(w*.62,h*.205),rows=[['L',.36,.11,-9],['A',.62,.275,7],['T',.38,.445,-6],['E',.63,.615,8],['L',.37,.785,-7],['Y',.62,.945,9]];return{size,rows}}
function maskData(o){if(!o.maskText)return'';const w=Math.max(1,Math.round(o.w)),h=Math.max(1,Math.round(o.h)),m=maskLayout(w,h),font='Marker Felt, Chalkboard SE, Arial Rounded MT Bold, Trebuchet MS, sans-serif';const texts=m.rows.map(([ch,x,y,r])=>`<text x="${x*w}" y="${y*h}" text-anchor="middle" dominant-baseline="middle" transform="rotate(${r} ${x*w} ${y*h})" font-family="${font}" font-size="${m.size}" font-weight="900" fill="white">${ch}</text>`).join(''),svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${texts}</svg>`;return`url("data:image/svg+xml,${encodeURIComponent(svg)}")`}
function applyMaskStyle(c,o){if(!o.maskText)return;c.classList.add('washi-text-mask');const d=maskData(o);c.style.webkitMaskImage=d;c.style.maskImage=d;c.style.webkitMaskRepeat='no-repeat';c.style.maskRepeat='no-repeat';c.style.webkitMaskSize='100% 100%';c.style.maskSize='100% 100%';c.style.webkitMaskPosition='center';c.style.maskPosition='center'}
function styleNode(n,o){n.style.left=`${o.x}px`;n.style.top=`${o.y}px`;n.style.width=`${o.w}px`;n.style.height=`${o.h}px`;n.style.transform=`rotate(${o.rotation||0}deg)`;n.style.opacity=o.opacity??1;n.style.zIndex=String((state.project.objects.findIndex(x=>x.id===o.id)+5))}
async function media(c,o,n){const url=await DB.assetURL(o.mediaId);if(!url||!document.body.contains(n))return;c.innerHTML='';const m=o.type==='video'?document.createElement('video'):new Image();m.src=url;if(m.tagName==='VIDEO'){m.playsInline=true;m.muted=o.muted!==false;m.loop=true;m.preload='metadata';c.classList.add('video-wrap')}else{m.alt='';m.draggable=false}m.style.width='100%';m.style.height='100%';m.style.objectFit=o.fit||'cover';m.style.objectPosition=`${o.focusX??50}% ${o.focusY??50}%`;m.style.transform=`scaleX(${o.flipX?-1:1}) scaleY(${o.flipY?-1:1})`;m.style.filter=filterCSS(o);c.append(m);applyMaskStyle(c,o)}
function content(c,o,n){if(o.type==='text'){c.classList.add('text-object');c.textContent=o.text||'Text';Object.assign(c.style,{fontFamily:o.font||'Georgia, serif',fontSize:`${o.fontSize||60}px`,color:o.color||'#4b3740',fontWeight:o.bold?'800':'400',fontStyle:o.italic?'italic':'normal',letterSpacing:`${o.letterSpacing||0}px`,lineHeight:o.lineHeight||1.1,textAlign:o.align||'left'});if(o.effect==='outline')c.style.webkitTextStroke=`${Math.max(1,(o.fontSize||50)*.035)}px ${o.outlineColor||'#fff'}`;if(o.effect==='shadow')c.style.textShadow='4px 5px 10px rgba(60,40,48,.3)';if(o.effect==='glow')c.style.textShadow=`0 0 18px ${o.outlineColor||'#fff'}`;if(o.effect==='highlight'||o.effect==='sticker'){c.style.background=o.highlightColor||'#fff0a8';c.style.padding='8px 12px';c.style.borderRadius=o.effect==='sticker'?'999px':'8px'}}else if(o.type==='sticker'){c.classList.add('sticker-object');c.textContent=o.content||'✦';c.style.fontSize=`${o.fontSize||80}px`;c.style.color=o.color||'#c84f77'}else if(o.type==='shape'){c.classList.add('shape-object');c.style.background=o.fill||'#fdeef4';c.style.border=`${o.borderWidth||0}px solid ${o.border||'transparent'}`;c.style.borderRadius=o.shape==='circle'?'50%':`${o.radius||0}px`}else if(o.type==='placeholder'&&!o.mediaId){c.classList.add('placeholder-object');c.style.borderRadius=`${o.radius||0}px`;if(o.maskText){c.style.background='linear-gradient(145deg,#f7b7c9,#c84f77)';applyMaskStyle(c,o)}else c.innerHTML='<b>＋</b><small>Add photo</small>'}else{c.style.borderRadius=`${o.radius||0}px`;media(c,o,n)}}
function make(o){const n=document.createElement('div');n.className=`layer-object${o.id===state.selectedId?' selected':''}${o.locked?' locked':''}${o.visible===false?' hidden-layer':''}`;n.dataset.objectId=o.id;styleNode(n,o);const c=document.createElement('div');c.className='object-content';n.append(c);content(c,o,n);if(o.maskText&&o.type==='placeholder'&&!o.mediaId){const p=document.createElement('span');p.className='washi-mask-prompt';p.textContent='＋ Add photo to LATELY';n.append(p)}for(const[h,t,cl]of[['resize','↘','resize-handle'],['rotate','↻','rotate-handle']]){const b=document.createElement('button');b.className=`object-handle ${cl}`;b.dataset.handle=h;b.textContent=t;n.append(b)}return n}
function pathData(a){if(!a?.length)return'';let d=`M ${a[0][0]} ${a[0][1]}`;for(let i=1;i<a.length;i++){const p=a[i-1],q=a[i];d+=` Q ${p[0]} ${p[1]} ${(p[0]+q[0])/2} ${(p[1]+q[1])/2}`}return d}
function stroke(s){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.classList.add('drawing-stroke');p.dataset.strokeId=s.id;p.setAttribute('d',pathData(s.points));p.setAttribute('stroke',s.color);p.setAttribute('stroke-width',s.width);p.setAttribute('opacity',s.opacity);return p}
function renderDraw(){el.drawingLayer.setAttribute('viewBox',`0 0 ${state.project.width} ${state.project.height}`);el.drawingLayer.innerHTML='';(state.project.drawings||[]).forEach(s=>el.drawingLayer.append(stroke(s)));el.drawingLayer.classList.toggle('draw-mode',state.draw.enabled)}
function render(){if(!state.project)return;cache();const p=state.project;el.projectTitle.textContent=p.name||'Untitled';el.projectSize.textContent=`${p.width} × ${p.height}`;setBackground();stageSize();const s=DB.getSettings();el.gridOverlay.classList.toggle('on',!!s.grid);el.safeZoneOverlay.classList.toggle('on',!!s.safeZones);el.objectsLayer.innerHTML='';(p.objects||[]).forEach(o=>el.objectsLayer.append(make(o)));renderDraw();selectionBar();undoUI();window.dispatchEvent(new CustomEvent('washi:selection-changed',{detail:{id:state.selectedId}}))}
function refreshSelected(){const o=selected();if(!o||!el.objectsLayer)return;const old=el.objectsLayer.querySelector(`[data-object-id="${CSS.escape(o.id)}"]`);if(old)old.replaceWith(make(o));else el.objectsLayer.append(make(o));selectionBar()}
function select(id){state.selectedId=id;render()}
function selectionBar(){const o=selected();if(!el.selectionBar)return;el.selectionBar.hidden=!o;if(o){const l=el.selectionBar.querySelector('[data-object-action="lock"]');if(l)l.textContent=o.locked?'Unlock':'Lock';const f=el.selectionBar.querySelector('[data-object-action="fill"]');if(f){f.hidden=!['placeholder','image','video'].includes(o.type);f.textContent=o.type==='placeholder'?'Fill':'Replace'}}}
function refreshObject(){refreshSelected()}
function updateSelected(patch,{history=true,rerender=true,persist=true}={}){const o=selected();if(!o)return;Object.assign(o,patch);if(rerender)refreshSelected();if(persist)save({history})}
function deleteSelected(){if(!state.selectedId)return;state.project.objects=state.project.objects.filter(o=>o.id!==state.selectedId);state.selectedId=null;render();save()}
function duplicateSelected(){const o=selected();if(!o)return;const c=DB.clone(o);c.id=DB.uid('obj');c.x+=28;c.y+=28;state.project.objects.push(c);state.selectedId=c.id;render();save();return c}
function rotate90(){const o=selected();if(o){o.rotation=((o.rotation||0)+90)%360;refreshSelected();save()}}
function centerSelected(){const o=selected();if(o){o.x=(state.project.width-o.w)/2;o.y=(state.project.height-o.h)/2;refreshSelected();save()}}
function reorder(id,d){const a=state.project.objects,i=a.findIndex(o=>o.id===id),j=clamp(i+d,0,a.length-1);if(i>=0&&i!==j){[a[i],a[j]]=[a[j],a[i]];render();save()}}
const bringForward=()=>reorder(state.selectedId,1),sendBackward=()=>reorder(state.selectedId,-1),moveLayer=reorder;
function toggleLock(){const o=selected();if(o){o.locked=!o.locked;refreshSelected();save()}}
function toggleVisible(id){const o=state.project.objects.find(x=>x.id===id);if(o){o.visible=o.visible===false;if(!o.visible&&state.selectedId===id)state.selectedId=null;render();save()}}
function addText(v='Text'){const o=T.addTextObject(state.project,v);state.selectedId=o.id;render();save();return o}
function addSticker(v){const z=state.project.width*.15,o={id:DB.uid('obj'),type:'sticker',content:v,x:state.project.width*.42,y:state.project.height*.34,w:z,h:z,fontSize:z*.82,color:'#c84f77',opacity:1,rotation:0,visible:true,locked:false};state.project.objects.push(o);state.selectedId=o.id;render();save();return o}
function addShape(kind='rect',fill='#fdeef4'){const w=state.project.width*.38,h=kind==='circle'?w:state.project.height*.12,o={id:DB.uid('obj'),type:'shape',shape:kind,x:(state.project.width-w)/2,y:state.project.height*.35,w,h,fill,border:'#fff',borderWidth:0,radius:kind==='circle'?999:28,opacity:1,rotation:0,visible:true,locked:false};state.project.objects.push(o);state.selectedId=o.id;render();save();return o}
function addTape(fill){const o=addShape('rect',fill);o.w=state.project.width*.34;o.h=Math.max(42,state.project.height*.035);o.rotation=-8;refreshSelected();save();return o}
function addPlaceholder(){const w=state.project.width*.68,h=state.project.height*.38,o={id:DB.uid('obj'),type:'placeholder',x:(state.project.width-w)/2,y:state.project.height*.22,w,h,radius:28,rotation:0,fit:'cover',opacity:1,visible:true,locked:false};state.project.objects.push(o);state.selectedId=o.id;render();save();return o}
async function optimize(file){if(!file.type.startsWith('image/')||file.type==='image/gif'||!window.createImageBitmap)return file;try{const b=await createImageBitmap(file),m=Math.max(b.width,b.height);if(m<=2600&&file.size<=3e6){b.close();return file}const k=Math.min(1,2600/m),c=document.createElement('canvas');c.width=Math.round(b.width*k);c.height=Math.round(b.height*k);c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close();const type=file.type==='image/png'?'image/png':'image/jpeg',blob=await new Promise(r=>c.toBlob(r,type,.9));return blob?new File([blob],file.name,{type:blob.type}):file}catch{return file}}
async function addMedia(files,{replaceSelected=false}={}){const out=[];for(const raw of files||[]){if(!/^(image|video)\//.test(raw.type))continue;const file=await optimize(raw),id=await DB.assetPut(file,{name:raw.name,type:file.type,size:file.size}),target=replaceSelected?selected():null;if(target&&target.type==='placeholder'){Object.assign(target,{mediaId:id,mediaType:file.type,type:file.type.startsWith('video/')?'video':'image',fit:target.fit||'cover',focusX:target.focusX??50,focusY:target.focusY??50,mediaZoom:target.mediaZoom??1});out.push(target);replaceSelected=false;continue}const w=state.project.width*.65,h=file.type.startsWith('video/')?state.project.height*.5:state.project.height*.42,o={id:DB.uid('obj'),type:file.type.startsWith('video/')?'video':'image',mediaId:id,mediaType:file.type,x:(state.project.width-w)/2,y:(state.project.height-h)/2,w,h,rotation:0,opacity:1,radius:18,fit:'cover',filterPreset:'none',brightness:1,contrast:1,saturation:1,focusX:50,focusY:50,mediaZoom:1,flipX:false,flipY:false,visible:true,locked:false,muted:true};state.project.objects.push(o);out.push(o)}if(out.length){state.selectedId=out.at(-1).id;render();save()}return out}
async function replaceSelectedMedia(file){const o=selected();if(!o||!file)return;const f=await optimize(file),id=await DB.assetPut(f,{name:file.name,type:f.type,size:f.size});Object.assign(o,{mediaId:id,mediaType:f.type,type:f.type.startsWith('video/')?'video':'image',fit:o.fit||'cover',filterPreset:'none',mediaZoom:o.mediaZoom??1,focusX:o.focusX??50,focusY:o.focusY??50});refreshSelected();save();return o}
function setBackgroundValue(v){state.project.bg=DB.clone(v);setBackground();save()}
function resizeProject(w,h){w=clamp(+w,320,5000);h=clamp(+h,320,5000);const sx=w/state.project.width,sy=h/state.project.height;state.project.objects.forEach(o=>{o.x*=sx;o.y*=sy;o.w*=sx;o.h*=sy;if(o.type==='text')o.fontSize*=Math.min(sx,sy)});state.project.drawings.forEach(s=>s.points=s.points.map(([x,y])=>[x*sx,y*sy]));state.project.width=w;state.project.height=h;render();fit();save()}
function point(x,y){const r=el.designStage.getBoundingClientRect();return{x:(x-r.left)/state.zoom,y:(y-r.top)/state.zoom}}
function keep(o){if(!DB.getSettings().keepInside)return;o.x=clamp(o.x,0,Math.max(0,state.project.width-o.w));o.y=clamp(o.y,0,Math.max(0,state.project.height-o.h))}
function snap(o){const g=el.alignmentGuides;g.className='alignment-guides';if(!DB.getSettings().snap)return;const t=14/state.zoom,cx=o.x+o.w/2,cy=o.y+o.h/2;if(Math.abs(cx-state.project.width/2)<t){o.x=state.project.width/2-o.w/2;g.classList.add('v')}if(Math.abs(cy-state.project.height/2)<t){o.y=state.project.height/2-o.h/2;g.classList.add('h')}}
function live(o){const n=el.objectsLayer.querySelector(`[data-object-id="${CSS.escape(o.id)}"]`);if(n)styleNode(n,o)}
function down(e){const n=e.target.closest('.layer-object');if(!n)return;const o=state.project.objects.find(x=>x.id===n.dataset.objectId);select(o.id);if(o.locked)return;e.preventDefault();n.setPointerCapture?.(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,id:o.id});const p=point(e.clientX,e.clientY),mode=e.target.closest('[data-handle]')?.dataset.handle||'drag';state.interaction={id:o.id,mode,startX:p.x,startY:p.y,base:DB.clone(o)};if(mode==='rotate')state.interaction.startAngle=Math.atan2(p.y-(o.y+o.h/2),p.x-(o.x+o.w/2))*180/Math.PI;el.designStage.classList.add('interacting')}
function move(e){if(!state.pointers.has(e.pointerId)||!state.interaction)return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,id:state.interaction.id});const pts=[...state.pointers.values()].filter(p=>p.id===state.interaction.id);if(pts.length>=2&&!['resize','rotate'].includes(state.interaction.mode)&&state.interaction.mode!=='pinch'){const a=point(pts[0].x,pts[0].y),b=point(pts[1].x,pts[1].y);state.interaction.mode='pinch';state.interaction.dist=Math.hypot(b.x-a.x,b.y-a.y);state.interaction.angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;state.interaction.base=DB.clone(selected())}if(!state.raf)state.raf=requestAnimationFrame(apply)}
function apply(){state.raf=0;const it=state.interaction,o=state.project.objects.find(x=>x.id===it?.id);if(!o)return;const pts=[...state.pointers.values()].filter(p=>p.id===it.id);if(it.mode==='pinch'&&pts.length>=2){const a=point(pts[0].x,pts[0].y),b=point(pts[1].x,pts[1].y),scale=clamp(Math.hypot(b.x-a.x,b.y-a.y)/it.dist,.2,5),ang=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,cx=it.base.x+it.base.w/2,cy=it.base.y+it.base.h/2;o.w=Math.max(40,it.base.w*scale);o.h=Math.max(40,it.base.h*scale);o.x=cx-o.w/2;o.y=cy-o.h/2;o.rotation=it.base.rotation+(ang-it.angle);keep(o);live(o);return}if(!pts[0])return;const p=point(pts[0].x,pts[0].y),b=it.base;if(it.mode==='drag'){o.x=b.x+p.x-it.startX;o.y=b.y+p.y-it.startY;snap(o);keep(o)}else if(it.mode==='resize'){o.w=Math.max(40,b.w+p.x-it.startX);o.h=Math.max(40,b.h+p.y-it.startY);keep(o)}else{o.rotation=b.rotation+(Math.atan2(p.y-(b.y+b.h/2),p.x-(b.x+b.w/2))*180/Math.PI-it.startAngle)}live(o)}
function up(e){if(!state.pointers.has(e.pointerId))return;state.pointers.delete(e.pointerId);if(!state.interaction)return;if(state.pointers.size===0||state.interaction.mode==='pinch'){state.pointers.clear();state.interaction=null;el.designStage.classList.remove('interacting');el.alignmentGuides.className='alignment-guides';save();render()}}
function drawDown(e){if(!state.draw.enabled)return;if(state.draw.brush==='eraser'){const p=e.target.closest?.('[data-stroke-id]');if(p){state.project.drawings=state.project.drawings.filter(s=>s.id!==p.dataset.strokeId);render();save()}return}e.preventDefault();const q=point(e.clientX,e.clientY),s={id:DB.uid('stroke'),brush:state.draw.brush,color:state.draw.color,width:state.draw.width,opacity:state.draw.brush==='highlighter'?.3:state.draw.opacity,points:[[q.x,q.y]]};state.project.drawings.push(s);state.draw.active=s;renderDraw()}
function drawMove(e){if(!state.draw.active)return;const q=point(e.clientX,e.clientY),a=state.draw.active.points,l=a.at(-1);if(Math.hypot(q.x-l[0],q.y-l[1])>2){a.push([q.x,q.y]);renderDraw()}}
function drawUp(){if(state.draw.active){state.draw.active=null;save()}}
function setDrawMode(enabled,opt={}){state.draw.enabled=enabled;Object.assign(state.draw,opt);if(enabled)state.selectedId=null;render()}
function clearDrawings(){state.project.drawings=[];render();save()}
function bind(){cache();el.objectsLayer.addEventListener('pointerdown',down);el.designStage.addEventListener('pointermove',move);el.designStage.addEventListener('pointerup',up);el.designStage.addEventListener('pointercancel',up);el.drawingLayer.addEventListener('pointerdown',drawDown);el.drawingLayer.addEventListener('pointermove',drawMove);el.drawingLayer.addEventListener('pointerup',drawUp);window.addEventListener('resize',()=>document.getElementById('editorView')?.classList.contains('active')&&fit(),{passive:true})}
W.Editor={state,bind,getProject,selected,objectLabel,setProject,openProject,createProject,createFromTemplate,save,undo,redo,render,fit,setZoom,select,updateSelected,deleteSelected,duplicateSelected,rotate90,centerSelected,bringForward,sendBackward,toggleLock,toggleVisible,refreshObject,moveLayer,addText,addSticker,addShape,addTape,addPlaceholder,addMedia,replaceSelectedMedia,setBackground:setBackgroundValue,resizeProject,setDrawMode,clearDrawings,filterCSS};
})();
