(() => {
  'use strict';
  const W=window.Washi=window.Washi||{}, DB=W.DB;
  const roundRect=(ctx,x,y,w,h,r)=>{r=Math.min(r||0,w/2,h/2);ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));};
  function paintBackground(ctx,p){const bg=p.bg||{type:'solid',value:'#fff'};ctx.save();if(bg.type==='solid'){ctx.fillStyle=bg.value;ctx.fillRect(0,0,p.width,p.height)}else if(bg.type==='gradient'){const stops=String(bg.value).match(/#[0-9a-f]{3,8}|rgba?\([^)]*\)/ig)||['#fff8fb','#f7b7c9'];const g=ctx.createLinearGradient(0,0,p.width,p.height);stops.slice(0,4).forEach((c,i,a)=>g.addColorStop(i/Math.max(1,a.length-1),c));ctx.fillStyle=g;ctx.fillRect(0,0,p.width,p.height)}else{ctx.fillStyle=bg.color||'#fffaf5';ctx.fillRect(0,0,p.width,p.height);ctx.strokeStyle='rgba(190,130,154,.18)';ctx.fillStyle='rgba(190,130,154,.18)';if(bg.value==='notebook'){ctx.lineWidth=2;for(let y=64;y<p.height;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(p.width,y);ctx.stroke()}}if(bg.value==='dots'){for(let y=18;y<p.height;y+=34)for(let x=18;x<p.width;x+=34){ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill()}}if(bg.value==='grid'){ctx.lineWidth=1;for(let y=0;y<p.height;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(p.width,y);ctx.stroke()}for(let x=0;x<p.width;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,p.height);ctx.stroke()}}}ctx.restore()}
  function fontString(o){return `${o.italic?'italic ':''}${o.bold?'800':'400'} ${Math.max(8,o.fontSize||60)}px ${o.font||'Georgia, serif'}`}
  function wrapLines(ctx,text,maxWidth){const out=[];String(text||'').split('\n').forEach(par=>{if(!par){out.push('');return}const words=par.split(/\s+/);let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){out.push(line);line=word}else line=test}out.push(line)});return out}
  function drawText(ctx,o){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.globalAlpha=o.opacity??1;ctx.font=fontString(o);ctx.textBaseline='top';ctx.textAlign=o.align||'left';const lines=wrapLines(ctx,o.text||'Text',Math.max(20,o.w)),lh=(o.fontSize||60)*(o.lineHeight||1.1),x=o.align==='center'?o.w/2:o.align==='right'?o.w:0;if(o.effect==='shadow'){ctx.shadowColor='rgba(64,40,49,.25)';ctx.shadowBlur=10;ctx.shadowOffsetX=4;ctx.shadowOffsetY=5}lines.forEach((line,i)=>{const y=i*lh,metrics=ctx.measureText(line),bx=o.align==='center'?(o.w-metrics.width)/2:o.align==='right'?o.w-metrics.width:0;if(o.effect==='highlight'||o.effect==='sticker'){ctx.save();ctx.shadowColor='transparent';ctx.fillStyle=o.highlightColor||(o.effect==='sticker'?'#fff':'#fff0a8');roundRect(ctx,bx-10,y-5,metrics.width+20,lh*.9,o.effect==='sticker'?lh*.45:8);ctx.fill();ctx.restore()}ctx.fillStyle=o.color||'#4b3740';if(o.effect==='outline'){ctx.lineWidth=Math.max(2,(o.fontSize||50)*.06);ctx.strokeStyle=o.outlineColor||'#fff';ctx.strokeText(line,x,y)}if(o.effect==='glow'){ctx.save();ctx.shadowColor=o.outlineColor||'#fff';ctx.shadowBlur=18;ctx.fillText(line,x,y);ctx.restore()}ctx.fillText(line,x,y)});ctx.restore()}
  function drawShape(ctx,o){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.globalAlpha=o.opacity??1;ctx.fillStyle=o.fill||'#fdeef4';ctx.strokeStyle=o.border||'transparent';ctx.lineWidth=o.borderWidth||0;if(o.shape==='circle'){ctx.beginPath();ctx.ellipse(o.w/2,o.h/2,o.w/2,o.h/2,0,0,Math.PI*2)}else roundRect(ctx,0,0,o.w,o.h,o.radius||0);ctx.fill();if((o.borderWidth||0)>0)ctx.stroke();ctx.restore()}
  function drawSticker(ctx,o){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.globalAlpha=o.opacity??1;ctx.font=`${o.fontSize||Math.min(o.w,o.h)*.8}px system-ui, Apple Color Emoji, Segoe UI Emoji`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=o.color||'#c84f77';ctx.fillText(o.content||'✦',0,0);ctx.restore()}
  async function loadImage(url){return await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url})}
  async function loadVideoFrame(url){return await new Promise((resolve,reject)=>{const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';const timer=setTimeout(()=>reject(new Error('video')),3500);v.onloadeddata=()=>{clearTimeout(timer);resolve(v)};v.onerror=()=>{clearTimeout(timer);reject(new Error('video'))};v.src=url;v.load()})}
  function coverRect(sw,sh,dw,dh,fit='cover',focusX=50,focusY=50){if(fit==='contain'){const s=Math.min(dw/sw,dh/sh),w=sw*s,h=sh*s;return{sx:0,sy:0,sw,sh,dx:(dw-w)/2,dy:(dh-h)/2,dw:w,dh:h}}const scale=Math.max(dw/sw,dh/sh),cw=dw/scale,ch=dh/scale,fx=Math.max(0,Math.min(1,focusX/100)),fy=Math.max(0,Math.min(1,focusY/100));return{sx:(sw-cw)*fx,sy:(sh-ch)*fy,sw:cw,sh:ch,dx:0,dy:0,dw,dh}}
  async function drawMedia(ctx,o){const url=await DB.assetURL(o.mediaId);if(!url)return;let m;try{m=o.type==='video'?await loadVideoFrame(url):await loadImage(url)}catch{return}const sw=o.type==='video'?(m.videoWidth||o.w):(m.naturalWidth||o.w),sh=o.type==='video'?(m.videoHeight||o.h):(m.naturalHeight||o.h);ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.globalAlpha=o.opacity??1;roundRect(ctx,0,0,o.w,o.h,o.radius||0);ctx.clip();if(o.flipX||o.flipY){ctx.translate(o.w/2,o.h/2);ctx.scale(o.flipX?-1:1,o.flipY?-1:1);ctx.translate(-o.w/2,-o.h/2)}const r=coverRect(sw,sh,o.w,o.h,o.fit||'cover',o.focusX??50,o.focusY??50);const preset={none:'none',soft:'brightness(1.05) saturate(.9) contrast(.96)',film:'contrast(1.08) saturate(.82) sepia(.12)',digicam:'contrast(1.12) saturate(1.18)',bw:'grayscale(1)',warm:'sepia(.14) saturate(1.05)',fade:'contrast(.88) saturate(.8) brightness(1.08)'};ctx.filter=o.filterPreset&&o.filterPreset!=='custom'?(preset[o.filterPreset]||'none'):`brightness(${o.brightness??1}) contrast(${o.contrast??1}) saturate(${o.saturation??1})`;ctx.drawImage(m,r.sx,r.sy,r.sw,r.sh,r.dx,r.dy,r.dw,r.dh);ctx.restore()}
  function drawPlaceholder(ctx,o){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.globalAlpha=o.opacity??1;ctx.setLineDash([18,12]);ctx.strokeStyle='rgba(200,79,119,.35)';ctx.lineWidth=4;ctx.fillStyle='rgba(255,239,245,.75)';roundRect(ctx,0,0,o.w,o.h,o.radius||20);ctx.fill();ctx.stroke();ctx.fillStyle='#c84f77';ctx.font='700 36px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.label||'Add photo',o.w/2,o.h/2);ctx.restore()}
  function drawStroke(ctx,s){if(!s.points?.length)return;ctx.save();ctx.globalAlpha=s.opacity??1;ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.lineCap=s.brush==='marker'?'square':'round';ctx.lineJoin='round';if(s.brush==='crayon')ctx.setLineDash([s.width*.7,s.width*.25]);ctx.beginPath();ctx.moveTo(...s.points[0]);for(let i=1;i<s.points.length;i++){const a=s.points[i-1],b=s.points[i];ctx.quadraticCurveTo(a[0],a[1],(a[0]+b[0])/2,(a[1]+b[1])/2)}ctx.stroke();ctx.restore()}
  async function renderProject(project,{scale=1}={}){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(project.width*scale));canvas.height=Math.max(1,Math.round(project.height*scale));const ctx=canvas.getContext('2d');ctx.scale(scale,scale);paintBackground(ctx,project);for(const o of project.objects||[]){if(o.visible===false)continue;if(o.type==='text')drawText(ctx,o);else if(o.type==='sticker')drawSticker(ctx,o);else if(o.type==='shape')drawShape(ctx,o);else if(o.type==='placeholder'&&!o.mediaId)drawPlaceholder(ctx,o);else await drawMedia(ctx,o)}(project.drawings||[]).forEach(s=>drawStroke(ctx,s));return canvas}
  W.Export={renderProject};
})();