(() => {
'use strict';
const W=window.Washi=window.Washi||{},DB=W.DB;
const rr=(c,x,y,w,h,r)=>{c.beginPath();c.roundRect?c.roundRect(x,y,w,h,Math.min(r||0,w/2,h/2)):c.rect(x,y,w,h)};
function bg(c,p){const b=p.bg||{type:'solid',value:'#fff'};if(b.type==='solid'){c.fillStyle=b.value;c.fillRect(0,0,p.width,p.height);return}if(b.type==='gradient'){const colors=String(b.value).match(/#[0-9a-f]{3,8}|rgba?\([^)]*\)/ig)||['#fff8fb','#f7b7c9'],g=c.createLinearGradient(0,0,p.width,p.height);colors.slice(0,4).forEach((x,i,a)=>g.addColorStop(i/Math.max(1,a.length-1),x));c.fillStyle=g;c.fillRect(0,0,p.width,p.height);return}c.fillStyle=b.color||'#fffaf5';c.fillRect(0,0,p.width,p.height);c.strokeStyle='rgba(190,130,154,.18)';c.fillStyle='rgba(190,130,154,.18)';if(b.value==='notebook'){for(let y=64;y<p.height;y+=64){c.beginPath();c.moveTo(0,y);c.lineTo(p.width,y);c.stroke()}}if(b.value==='dots')for(let y=18;y<p.height;y+=34)for(let x=18;x<p.width;x+=34){c.beginPath();c.arc(x,y,2,0,Math.PI*2);c.fill()}if(b.value==='grid'){for(let y=0;y<p.height;y+=60){c.beginPath();c.moveTo(0,y);c.lineTo(p.width,y);c.stroke()}for(let x=0;x<p.width;x+=60){c.beginPath();c.moveTo(x,0);c.lineTo(x,p.height);c.stroke()}}}
function lines(c,t,w){const out=[];String(t||'').split('\n').forEach(p=>{let line='';for(const word of p.split(/\s+/)){const q=line?`${line} ${word}`:word;if(line&&c.measureText(q).width>w){out.push(line);line=word}else line=q}out.push(line)});return out}
function text(c,o){c.save();c.translate(o.x+o.w/2,o.y+o.h/2);c.rotate((o.rotation||0)*Math.PI/180);c.translate(-o.w/2,-o.h/2);c.globalAlpha=o.opacity??1;c.font=`${o.italic?'italic ':''}${o.bold?'800':'400'} ${o.fontSize||60}px ${o.font||'Georgia, serif'}`;c.textBaseline='top';c.textAlign=o.align||'left';const lh=(o.fontSize||60)*(o.lineHeight||1.1),x=o.align==='center'?o.w/2:o.align==='right'?o.w:0;if(o.effect==='shadow'){c.shadowColor='rgba(64,40,49,.28)';c.shadowBlur=10;c.shadowOffsetX=4;c.shadowOffsetY=5}lines(c,o.text||'Text',o.w).forEach((s,i)=>{const y=i*lh,m=c.measureText(s),bx=o.align==='center'?(o.w-m.width)/2:o.align==='right'?o.w-m.width:0;if(['highlight','sticker'].includes(o.effect)){c.save();c.shadowColor='transparent';c.fillStyle=o.highlightColor||(o.effect==='sticker'?'#fff':'#fff0a8');rr(c,bx-10,y-5,m.width+20,lh*.9,o.effect==='sticker'?lh*.45:8);c.fill();c.restore()}c.fillStyle=o.color||'#4b3740';if(o.effect==='outline'){c.strokeStyle=o.outlineColor||'#fff';c.lineWidth=Math.max(2,(o.fontSize||50)*.06);c.strokeText(s,x,y)}if(o.effect==='glow'){c.save();c.shadowColor=o.outlineColor||'#fff';c.shadowBlur=18;c.fillText(s,x,y);c.restore()}c.fillText(s,x,y)});c.restore()}
function shape(c,o){c.save();c.translate(o.x+o.w/2,o.y+o.h/2);c.rotate((o.rotation||0)*Math.PI/180);c.translate(-o.w/2,-o.h/2);c.globalAlpha=o.opacity??1;c.fillStyle=o.fill||'#fdeef4';c.strokeStyle=o.border||'transparent';c.lineWidth=o.borderWidth||0;if(o.shape==='circle'){c.beginPath();c.ellipse(o.w/2,o.h/2,o.w/2,o.h/2,0,0,Math.PI*2)}else rr(c,0,0,o.w,o.h,o.radius||0);c.fill();if(o.borderWidth)c.stroke();c.restore()}
function sticker(c,o){c.save();c.translate(o.x+o.w/2,o.y+o.h/2);c.rotate((o.rotation||0)*Math.PI/180);c.globalAlpha=o.opacity??1;c.font=`${o.fontSize||Math.min(o.w,o.h)*.8}px system-ui,Apple Color Emoji,Segoe UI Emoji`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=o.color||'#c84f77';c.fillText(o.content||'✦',0,0);c.restore()}
const image=u=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=u});const video=u=>new Promise((res,rej)=>{const v=document.createElement('video'),t=setTimeout(()=>rej(new Error('video')),3500);v.muted=true;v.playsInline=true;v.onloadeddata=()=>{clearTimeout(t);res(v)};v.onerror=rej;v.src=u;v.load()});
function crop(sw,sh,dw,dh,fit='cover',fx=50,fy=50){if(fit==='contain'){const s=Math.min(dw/sw,dh/sh),w=sw*s,h=sh*s;return[0,0,sw,sh,(dw-w)/2,(dh-h)/2,w,h]}const s=Math.max(dw/sw,dh/sh),cw=dw/s,ch=dh/s;return[(sw-cw)*fx/100,(sh-ch)*fy/100,cw,ch,0,0,dw,dh]}
async function media(c,o){const u=await DB.assetURL(o.mediaId);if(!u)return;let m;try{m=o.type==='video'?await video(u):await image(u)}catch{return}const sw=o.type==='video'?(m.videoWidth||o.w):(m.naturalWidth||o.w),sh=o.type==='video'?(m.videoHeight||o.h):(m.naturalHeight||o.h);c.save();c.translate(o.x+o.w/2,o.y+o.h/2);c.rotate((o.rotation||0)*Math.PI/180);c.translate(-o.w/2,-o.h/2);c.globalAlpha=o.opacity??1;rr(c,0,0,o.w,o.h,o.radius||0);c.clip();if(o.flipX||o.flipY){c.translate(o.w/2,o.h/2);c.scale(o.flipX?-1:1,o.flipY?-1:1);c.translate(-o.w/2,-o.h/2)}const p={none:'none',soft:'brightness(1.05) saturate(.9) contrast(.96)',film:'contrast(1.08) saturate(.82) sepia(.12)',digicam:'contrast(1.12) saturate(1.18)',bw:'grayscale(1)',warm:'sepia(.14) saturate(1.05)',fade:'contrast(.88) saturate(.8) brightness(1.08)'};c.filter=o.filterPreset&&o.filterPreset!=='custom'?(p[o.filterPreset]||'none'):`brightness(${o.brightness??1}) contrast(${o.contrast??1}) saturate(${o.saturation??1})`;c.drawImage(m,...crop(sw,sh,o.w,o.h,o.fit||'cover',o.focusX??50,o.focusY??50));c.restore()}
function placeholder(c,o){c.save();c.translate(o.x+o.w/2,o.y+o.h/2);c.rotate((o.rotation||0)*Math.PI/180);c.translate(-o.w/2,-o.h/2);c.setLineDash([18,12]);c.strokeStyle='rgba(200,79,119,.35)';c.lineWidth=4;c.fillStyle='rgba(255,239,245,.75)';rr(c,0,0,o.w,o.h,o.radius||20);c.fill();c.stroke();c.fillStyle='#c84f77';c.font='700 36px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(o.label||'Add photo',o.w/2,o.h/2);c.restore()}
function stroke(c,s){if(!s.points?.length)return;c.save();c.globalAlpha=s.opacity??1;c.strokeStyle=s.color;c.lineWidth=s.width;c.lineCap=s.brush==='marker'?'square':'round';c.lineJoin='round';if(s.brush==='crayon')c.setLineDash([s.width*.7,s.width*.25]);c.beginPath();c.moveTo(...s.points[0]);for(let i=1;i<s.points.length;i++){const a=s.points[i-1],b=s.points[i];c.quadraticCurveTo(a[0],a[1],(a[0]+b[0])/2,(a[1]+b[1])/2)}c.stroke();c.restore()}
async function renderProject(p){const canvas=document.createElement('canvas');canvas.width=p.width;canvas.height=p.height;const c=canvas.getContext('2d');bg(c,p);for(const o of p.objects||[]){if(o.visible===false)continue;if(o.type==='text')text(c,o);else if(o.type==='shape')shape(c,o);else if(o.type==='sticker')sticker(c,o);else if(o.type==='placeholder'&&!o.mediaId)placeholder(c,o);else await media(c,o)}(p.drawings||[]).forEach(s=>stroke(c,s));return canvas}
const blob=(c,t,q)=>new Promise(r=>c.toBlob(r,t,q));async function exportProject(p,{format='png',quality=.94,share=false}={}){const c=await renderProject(p);let mime=format==='jpg'?'image/jpeg':format==='webp'?'image/webp':'image/png',ext=format==='jpg'?'jpg':format==='webp'?'webp':'png',b=await blob(c,mime,quality);if(!b&&format==='webp'){mime='image/png';ext='png';b=await blob(c,mime,quality)}if(!b)throw new Error('Export failed');const name=((p.name||'Washi Design').replace(/[^\w\- ]+/g,'').trim().replace(/\s+/g,'-')||'washi-design')+'.'+ext,file=new File([b],name,{type:mime});if(share&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:p.name||'Washi design'});return{file,shared:true,url:null}}return{file,shared:false,url:URL.createObjectURL(b)}}
W.Export={renderProject,exportProject};
})();