(() => {
'use strict';
const css=document.createElement('style');css.textContent=`
.hero-card{padding:14px 16px 13px;border-radius:20px}.hero-card:after{right:12px;top:4px;font-size:2.15rem}.hero-card h1{margin:0 0 5px;font-size:clamp(1.5rem,5.8vw,2.05rem);line-height:1}.hero-card p{margin:0 0 9px;max-width:31rem;font-size:.8rem;line-height:1.3}.soft-pill{margin-bottom:6px;padding:4px 8px;font-size:.62rem}.hero-actions{gap:6px}.hero-actions .primary-button,.hero-actions .secondary-button{min-height:36px;padding-inline:11px;font-size:.76rem;border-radius:13px}
.name-story-card{grid-template-columns:46px 1fr;gap:11px;margin-top:11px;padding:13px 14px;border-radius:19px}.name-story-mark{width:46px;height:46px;border-radius:14px;font-size:1.08rem}.name-story-card .section-kicker{font-size:.6rem}.name-story-card p{margin:2px 0 0;font-size:.79rem;line-height:1.34}.home-section{margin-top:20px}
@media(max-width:430px){.hero-card{padding:11px 12px 10px;border-radius:18px}.hero-card:after{right:9px;top:1px;font-size:1.7rem}.soft-pill{display:none}.hero-card h1{font-size:1.38rem;line-height:1.02;margin-bottom:5px;letter-spacing:-.035em}.hero-card h1 br{display:none}.hero-card h1 em:before{content:' '}.hero-card p{font-size:.71rem;line-height:1.23;margin-bottom:7px;max-width:94%}.hero-actions{gap:5px}.hero-actions .primary-button,.hero-actions .secondary-button{min-height:33px;padding-inline:9px;font-size:.69rem;border-radius:11px}.name-story-card{grid-template-columns:38px 1fr;gap:8px;margin-top:8px;padding:10px 11px;border-radius:16px}.name-story-mark{width:38px;height:38px;border-radius:12px;font-size:.92rem}.name-story-card .section-kicker{font-size:.54rem}.name-story-card p{margin-top:1px;font-size:.68rem;line-height:1.27}.home-section{margin-top:15px}}
body.washi-wallpaper-enabled{background:none!important;background-image:none!important}.app-shell{position:relative;z-index:1}.nav-create{border-color:var(--pink-50)!important}body.washi-wallpaper-enabled:before{content:"";position:fixed;inset:0;z-index:0;pointer-events:none;background-image:linear-gradient(rgba(255,250,253,var(--washi-wallpaper-overlay,.48)),rgba(255,247,250,var(--washi-wallpaper-overlay,.48))),var(--washi-wallpaper-url);background-size:cover;background-position:center;background-repeat:no-repeat}
`;document.head.append(css);window.Washi=window.Washi||{};window.Washi.HomeCompact={version:'v1.0'};
})();
