(() => {
'use strict';
const W=window.Washi=window.Washi||{},DB=W.DB;if(!DB)return;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let mode=false;const selected=new Set();
function ensure(){const v=$('#projectsView');if(!v)return;const h=v.querySelector('.page-heading.with-action');if(h&&!$('#washiProjectHeadingActions')){const n=h.querySelector('[data-action="new-project"]'),a=document.createElement('div');a.id='washiProjectHeadingActions';a.className='washi-project-heading-actions';const s=document.createElement('button');s.type='button';s.className='secondary-button washi-select-projects';s.dataset.washiProjectSelectToggle='1';s.textContent='Select';a.append(s);if(n)a.append(n);h.append(a)}const tools=v.querySelector('.project-tools');if(tools&&!$('#washiProjectBatchBar')){const b=document.createElement('div');b.id='washiProjectBatchBar';b.className='washi-project-batch';b.hidden=true;b.innerHTML='<strong data-project-selected-count>0 selected</strong><div><button type="button" data-project-select-all>Select all</button><button type="button" class="danger" data-project-delete-selected disabled>Delete</button><button type="button" data-project-select-cancel>Cancel</button></div>';tools.insertAdjacentElement('afterend',b)}}
const idOf=c=>c?.querySelector('[data-open-project]')?.dataset.openProject||null;
function sync(){ensure();const g=$('#allProjects'),bar=$('#washiProjectBatchBar'),toggle=$('[data-washi-project-select-toggle]');if(!g)return;g.classList.toggle('project-select-mode',mode);$$('#allProjects .project-card').forEach(c=>{const id=idOf(c);if(!id)return;c.dataset.projectId=id;let k=c.querySelector('[data-project-select-check]');if(!k){k=document.createElement('button');k.type='button';k.className='project-select-check';k.dataset.projectSelectCheck=id;k.setAttribute('aria-label','Select project');c.prepend(k)}k.hidden=!mode;const on=selected.has(id);k.textContent=on?'✓':'';k.classList.toggle('on',on);k.setAttribute('aria-pressed',String(on));c.classList.toggle('selected-project',on)});if(toggle)toggle.textContent=mode?'Done':'Select';if(bar){bar.hidden=!mode;const c=bar.querySelector('[data-project-selected-count]');if(c)c.textContent=`${selected.size} selected`;const d=bar.querySelector('[data-project-delete-selected]');if(d)d.disabled=selected.size===0}}
function toggle(id){if(!id)return;selected.has(id)?selected.delete(id):selected.add(id);sync()}
function cancel(){mode=false;selected.clear();sync()}
function refresh(){const s=$('#projectSearch');s?s.dispatchEvent(new Event('input',{bubbles:true})):requestAnimationFrame(sync)}
function remove(){const ids=[...selected];if(!ids.length)return;if(!confirm(`Delete ${ids.length} selected project${ids.length===1?'':'s'}? This cannot be undone.`))return;ids.forEach(id=>DB.deleteProject?.(id));selected.clear();refresh()}
document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;if(mode){const b=t.closest('#allProjects [data-open-project]');if(b){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();toggle(b.dataset.openProject)}}},true);
document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;if(t.closest('[data-washi-project-select-toggle]')){mode=!mode;if(!mode)selected.clear();sync();return}const c=t.closest('[data-project-select-check]');if(c){e.preventDefault();toggle(c.dataset.projectSelectCheck);return}if(t.closest('[data-project-select-all]')){$$('#allProjects [data-open-project]').forEach(b=>selected.add(b.dataset.openProject));sync();return}if(t.closest('[data-project-delete-selected]')){remove();return}if(t.closest('[data-project-select-cancel]')){cancel();return}const r=t.closest('[data-route]')?.dataset.route;if(r&&r!=='projects'&&mode)cancel();if(r==='projects'||t.closest('[data-project-action]'))requestAnimationFrame(sync)});
document.addEventListener('input',e=>{if(e.target?.id==='projectSearch')requestAnimationFrame(sync)});document.addEventListener('change',e=>{if(e.target?.id==='projectSort')requestAnimationFrame(sync)});
const css=document.createElement('style');css.textContent=`.washi-project-heading-actions{display:flex;gap:7px;align-items:center}.washi-select-projects{min-height:42px;padding:0 13px}.washi-project-batch{margin:-2px 0 13px;padding:10px 11px;border:1px solid rgba(200,79,119,.18);border-radius:16px;background:rgba(255,249,252,.92);display:flex;align-items:center;justify-content:space-between;gap:8px}.washi-project-batch[hidden]{display:none}.washi-project-batch strong{font-size:.76rem}.washi-project-batch>div{display:flex;gap:5px;overflow-x:auto}.washi-project-batch button{min-height:35px;border:1px solid var(--line);border-radius:10px;background:#fff;padding:0 9px;font-size:.68rem;font-weight:800;white-space:nowrap}.washi-project-batch button.danger{color:#ae3157;background:#fff5f8}.project-card{position:relative}.project-select-check{position:absolute;z-index:8;top:9px;left:9px;width:34px;height:34px;border:2px solid #fff;border-radius:11px;background:rgba(255,255,255,.94);box-shadow:0 4px 12px rgba(70,40,50,.15);color:#fff;font-weight:900}.project-select-check.on{background:var(--rose)}.project-select-mode .project-card-actions{opacity:.28;pointer-events:none}.project-card.selected-project{outline:3px solid rgba(200,79,119,.55);outline-offset:-3px;background:#fff7fa}@media(max-width:430px){.washi-project-heading-actions{gap:5px}.washi-select-projects,.washi-project-heading-actions .primary-button{padding-inline:10px}.washi-project-batch{align-items:flex-start;flex-direction:column}.washi-project-batch>div{width:100%}.washi-project-batch button{flex:1}}`;document.head.append(css);
function boot(){ensure();sync();W.ProjectBatch={version:'v1.0',sync,cancel}}
if(document.readyState==='complete')boot();else window.addEventListener('load',boot,{once:true});
})();
