  function pushHistory(){const p=getProject();if(!p)return;const snap=deepClone(p);state.history=state.history.slice(0,state.historyIndex+1);state.history.push(snap);if(state.history.length>40)state.history.shift();state.historyIndex=state.history.length-1;}
  function restoreHistory(index){if(index<0||index>=state.history.length)return;const snap=deepClone(state.history[index]);const idx=projects.findIndex(p=>p.id===snap.id);if(idx<0)return;projects[idx]=snap;state.historyIndex=index;saveProjects();renderEditor();loadDrawing();}
  function undo(){if(state.historyIndex<=0)return;restoreHistory(state.historyIndex-1);}
  function redo(){if(state.historyIndex>=state.history.length-1)return;restoreHistory(state.historyIndex+1);}

  function fitStage(){const p=getProject();if(!p)return;const viewportW=window.innerWidth-70;const viewportH=Math.max(280,window.innerHeight-370);const fit=Math.min(viewportW/p.width,viewportH/p.height,1);state.zoom=clamp(fit,.08,1.5);applyStageScale();}
  function applyStageScale(){const p=getProject();if(!p)return;const frame=$("#stageFrame"),stage=$("#designStage");frame.style.width=`${p.width*state.zoom}px`;frame.style.height=`${p.height*state.zoom}px`;stage.style.width=`${p.width}px`;stage.style.height=`${p.height}px`;stage.style.transform=`scale(${state.zoom})`;$("#zoomLabel").textContent=`${Math.round(state.zoom*100)}%`;const draw=$("#drawCanvas");if(draw.width!==p.width||draw.height!==p.height){draw.width=p.width;draw.height=p.height;}}
  function setBackground(stage,p){const bg=p.bg||{type:"solid",value:"#fff"};stage.style.background="";stage.style.backgroundColor="";stage.style.backgroundImage="";stage.style.backgroundSize="";if(bg.type==="solid")stage.style.backgroundColor=bg.value;if(bg.type==="gradient")stage.style.background=bg.value;if(bg.type==="pattern"){stage.style.backgroundColor=bg.color||"#fffdf8";if(bg.value==="notebook"){stage.style.backgroundImage="repeating-linear-gradient(0deg,transparent 0 62px,rgba(190,130,154,.17) 63px 65px)";}else if(bg.value==="dots"){stage.style.backgroundImage="radial-gradient(rgba(195,79,119,.22) 2px,transparent 2px)";stage.style.backgroundSize="34px 34px";}else if(bg.value==="grid"){stage.style.backgroundImage="linear-gradient(rgba(195,79,119,.13) 2px,transparent 2px),linear-gradient(90deg,rgba(195,79,119,.13) 2px,transparent 2px)";stage.style.backgroundSize="60px 60px";}}}
  function objectTransform(o){return `translate(${o.x}px,${o.y}px) rotate(${o.rotation||0}deg)`;}
  function filterValue(o){if(o.filterPreset&&FILTER_PRESETS[o.filterPreset])return FILTER_PRESETS[o.filterPreset].filter;const b=o.brightness??1,c=o.contrast??1,s=o.saturation??1,sep=o.sepia??0,g=o.grayscale??0,blur=o.blur??0;return `brightness(${b}) contrast(${c}) saturate(${s}) sepia(${sep}) grayscale(${g}) blur(${blur}px)`;}

  async function renderObjectMedia(el,o){const content=$(".object-content",el);const url=await assetURL(o.mediaId);if(!url||!document.body.contains(el))return;if(o.mediaType?.startsWith("video")||o.type==="video"){const video=document.createElement("video");video.src=url;video.muted=o.muted!==false;video.loop=true;video.playsInline=true;video.preload="metadata";video.playbackRate=o.playbackRate||1;video.style.objectFit=o.fit||"cover";video.style.filter=filterValue(o);video.dataset.objectVideo=o.id;content.innerHTML="";content.append(video);}else{const img=document.createElement("img");img.src=url;img.alt="";img.draggable=false;img.style.objectFit=o.fit||"cover";img.style.filter=filterValue(o);content.innerHTML="";content.append(img);}}
  function renderTextContent(content,o){content.className="object-content text-content";content.textContent=o.text||"Text";content.style.fontFamily=o.font;content.style.fontSize=`${o.fontSize}px`;content.style.color=o.color;content.style.textAlign=o.align;content.style.justifyContent=o.align==="center"?"center":o.align==="right"?"flex-end":"flex-start";content.style.fontWeight=o.bold?"800":"400";content.style.fontStyle=o.italic?"italic":"normal";content.style.letterSpacing=`${o.letterSpacing||0}px`;content.style.lineHeight=o.lineHeight||1.1;content.style.background=o.background||"transparent";content.style.borderRadius=`${o.radius||0}px`;content.style.padding=o.effect==="highlight"||o.effect==="sticker"?"12px 18px":"0";content.style.webkitTextStroke="";content.style.textShadow="";content.style.transform="";if(o.effect==="outline")content.style.webkitTextStroke=`${Math.max(2,o.fontSize*.035)}px ${o.outline||"#fff"}`;if(o.effect==="shadow")content.style.textShadow=`${o.fontSize*.06}px ${o.fontSize*.08}px ${o.fontSize*.08}px ${o.shadow||"rgba(0,0,0,.2)"}`;if(o.effect==="glow")content.style.textShadow=`0 0 ${o.fontSize*.22}px ${o.outline||"#fff"}`;if(o.effect==="highlight")content.style.background=o.background==="transparent"?"rgba(255,231,139,.7)":o.background;if(o.effect==="sticker"){content.style.background=o.background==="transparent"?"#fff":o.background;content.style.boxShadow=`0 ${o.fontSize*.08}px ${o.fontSize*.2}px rgba(80,45,58,.12)`;content.style.borderRadius="999px";}if(o.effect==="arc")content.style.transform="rotate(-4deg) skewX(-3deg)";if(o.effect==="wave")content.style.transform="skewY(-3deg)";}
  function makeObjectElement(o){const el=document.createElement("div");el.className=`design-object ${state.selectedIds.includes(o.id)?"selected":""} ${o.locked?"locked":""} ${o.visible===false?"hidden-object":""}`;el.dataset.objectId=o.id;el.style.width=`${o.w}px`;el.style.height=`${o.h}px`;el.style.transform=objectTransform(o);el.style.opacity=o.opacity??1;const content=document.createElement("div");content.className="object-content";el.append(content);
    if(o.type==="text")renderTextContent(content,o);
    else if(o.type==="sticker"){content.textContent=o.content;content.style.fontSize=`${o.fontSize||o.h*.78}px`;content.style.color=o.color||"#c34f77";}
    else if(o.type==="shape"){content.style.background=o.fill;content.style.border=`${o.borderWidth||0}px solid ${o.border||"transparent"}`;content.style.borderRadius=o.shape==="circle"?"50%":`${o.radius||0}px`;}
    else if(o.type==="placeholder"&&!o.mediaId){content.className="object-content placeholder-content";content.innerHTML=`<b>＋</b><small>${escapeHTML(o.label||"Add photo")}</small>`;}
    else renderObjectMedia(el,o);
    if(o.type==="placeholder"&&o.mediaId)renderObjectMedia(el,o);
    const resize=document.createElement("button");resize.className="resize-handle";resize.dataset.handle="resize";resize.setAttribute("aria-label","Resize");resize.textContent="↘";el.append(resize);const rotate=document.createElement("button");rotate.className="rotate-handle";rotate.dataset.handle="rotate";rotate.setAttribute("aria-label","Rotate");rotate.textContent="↻";el.append(rotate);return el;}

  function renderEditor(){const p=getProject();if(!p)return;$("#projectTitle").textContent=p.name;$("#projectSizeLabel").textContent=`${p.width} × ${p.height}`;const stage=$("#designStage");setBackground(stage,p);$("#gridOverlay").classList.toggle("on",settings.grid);$("#safeZoneOverlay").classList.toggle("on",settings.safeZones);const root=$("#objectsLayer");root.innerHTML="";(p.objects||[]).forEach(o=>root.append(makeObjectElement(o)));applyStageScale();$("#undoButton").disabled=state.historyIndex<=0;$("#redoButton").disabled=state.historyIndex>=state.history.length-1;if(state.panelTool)renderPanel(state.panelTool);}
