(() => {
  'use strict';
  const W = window.Washi = window.Washi || {};
  const $ = (s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
  const uid=(p='obj')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const clone=o=>JSON.parse(JSON.stringify(o));
  const mediaUrls=new Map(),activePointers=new Map();
  let interaction=null,gesture=null,drawSession=null;
  const state=()=>W.state;
  const project=()=>state()?.projects?.find(p=>p.id===state().currentProjectId)||null;
  const selected=()=>project()?.objects?.find(o=>o.id===state().selectedIds?.[0])||null;
  const settings=()=>state()?.settings||W.Store.settings();
  const save=()=>{W.persistProjects?.();W.renderProjectLists?.()};
  const pushHistory=()=>{const p=project();if(!p)return;const snap=JSON.stringify({background:p.background,objects:p.objects}),h=state().history;if(h[h.length-1]===snap)return;h.push(snap);if(h.length>40)h.shift();state().future=[]};
  const commit=(fn,{render=true,history=true}={})=>{const p=project();if(!p)return;fn(p);p.updatedAt=new Date().toISOString();save();if(history)pushHistory();if(render)renderEditor()};
  const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function objName(o){if(o.name)return o.name;if(o.type==='text')return(o.text||'Text').slice(0,28);if(o.type==='sticker')return`Sticker ${o.value||'✦'}`;if(o.type==='image')return'Photo';if(o.type==='video')return'Video';if(o.type==='frame')return'Photo frame';if(o.type==='drawing')return'Drawing';return o.type||'Layer'}
  function transform(o){return`translate3d(${o.x||0}px,${o.y||0}px,0) rotate(${o.rotation||0}deg) scale(${o.flipX?-1:1},${o.flipY?-1:1})`}
  function filter(o){return`brightness(${o.brightness??100}%) contrast(${o.contrast??100}%) saturate(${o.saturation??100}%) sepia(${o.sepia??0}%) blur(${o.blur??0}px)`}
  function textShadow(o){if(o.effect==='outline')return'-2px -2px 0 #fff,2px -2px 0 #fff,-2px 2px 0 #fff,2px 2px 0 #fff';if(o.effect==='shadow')return'4px 5px 0 rgba(90,50,65,.22)';if(o.effect==='glow')return`0 0 10px ${o.glowColor||'#fff'},0 0 22px ${o.glowColor||'#fff'}`;if(o.effect==='offset')return'5px 5px 0 rgba(216,100,137,.45)';return'none'}
  async function urlFor(id){if(!id)return null;if(mediaUrls.has(id))return mediaUrls.get(id);const rec=await W.MediaDB.get(id);if(!rec?.blob)return null;const url=URL.createObjectURL(rec.blob);mediaUrls.set(id,url);return url}
  function objectHTML(o){const common=`data-object-id="${o.id}" class="canvas-object ${state().selectedIds.includes(o.id)?'selected':''} ${o.locked?'locked':''}" style="width:${o.w}px;height:${o.h}px;transform:${transform(o)};opacity:${o.opacity??1};display:${o.hidden?'none':'block'};z-index:${o.z||1}"`;let content='';if(o.type==='text'){const bg=o.effect==='highlight'?(o.highlightColor||'#ffe1a8'):'transparent';content=`<div class="object-content text-content" style="font-family:${o.fontFamily||'Georgia, serif'};font-size:${o.fontSize||60}px;font-weight:${o.fontWeight||500};font-style:${o.italic?'italic':'normal'};line-height:${o.lineHeight||1.1};letter-spacing:${o.letterSpacing||0}px;color:${o.color||'#543944'};text-align:${o.align||'left'};align-items:${o.verticalAlign==='middle'?'center':o.verticalAlign==='bottom'?'flex-end':'flex-start'};justify-content:${o.align==='center'?'center':o.align==='right'?'flex-end':'flex-start'};text-shadow:${textShadow(o)};-webkit-text-stroke:${o.strokeWidth||0}px ${o.strokeColor||'#fff'};background:${bg};border-radius:${o.effect==='sticker'?18:0}px;padding:${o.effect==='sticker'?12:0}px">${escapeHtml(o.text||'Text')}</div>`}else if(o.type==='sticker')content=`<div class="object-content sticker-content" style="font-size:${o.fontSize||Math.min(o.w,o.h)*.8}px">${escapeHtml(o.value||'✦')}</div>`;else if(o.type==='shape')content=`<div class="object-content shape-content" style="background:${o.color||'#f7bfd0'};border-radius:${o.shape==='circle'?'50%':(o.radius||24)+'px'};border:${o.borderWidth||0}px solid ${o.borderColor||'#fff'}"></div>`;else if(o.type==='frame')content=`<div class="object-content frame-content" style="border-radius:${o.radius||26}px"><span>＋ photo</span></div>`;else if(o.type==='image'||o.type==='video')content=`<div class="object-content media-content" style="border-radius:${o.radius||0}px;border:${o.borderWidth||0}px solid ${o.borderColor||'#fff'}"><${o.type==='video'?'video':'img'} data-media-id="${o.mediaId||''}" ${o.type==='video'?'muted playsinline loop':''} alt="" style="object-fit:${o.fit||'cover'};filter:${filter(o)};transform:translate(${o.mediaX||0}%,${o.mediaY||0}%) scale(${o.mediaScale||1});opacity:${o.mediaOpacity??1}"></${o.type==='video'?'video':'img'}></div>`;else if(o.type==='drawing'){const pts=(o.points||[]).map(p=>`${p.x},${p.y}`).join(' ');content=`<svg class="object-content drawing-content" viewBox="0 0 ${o.w} ${o.h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="${o.color||'#d96b8e'}" stroke-width="${o.strokeWidth||12}" stroke-linecap="round" stroke-linejoin="round" opacity="${o.opacity??1}" /></svg>`}return`<div ${common}>${content}<button class="object-handle handle-delete" data-handle="delete" aria-label="Delete">×</button><button class="object-handle handle-rotate" data-handle="rotate" aria-label="Rotate">↻</button><button class="object-handle handle-resize" data-handle="resize" aria-label="Resize">↘</button></div>`}
  function hydrateMedia(root=document){$$('[data-media-id]',root).forEach(async el=>{const id=el.dataset.mediaId;if(!id)return;const url=await urlFor(id);if(!url||!el.isConnected)return;el.src=url})}
  function fitZoom(){const p=project(),scroll=$('#stageScroll');if(!p||!scroll)return.25;const w=Math.max(260,scroll.clientWidth-58),h=Math.max(300,scroll.clientHeight-160);return clamp(Math.min(w/p.width,h/p.height),.12,.75)}
  function applyStage(){const p=project(),stage=$('#designStage'),frame=$('#stageFrame');if(!p||!stage||!frame)return;const z=state().zoom||fitZoom();state().zoom=z;frame.style.width=`${p.width*z}px`;frame.style.height=`${p.height*z}px`;stage.style.width=`${p.width}px`;stage.style.height=`${p.height}px`;stage.style.background=p.background||'#fff';stage.style.transform=`scale(${z})`;$('#zoomLabel').textContent=`${Math.round(z*100)}%`;$('#safeZoneOverlay').classList.toggle('show',!!settings().safeZones);$('#gridOverlay').classList.toggle('show',!!settings().grid)}
  function renderEditor(){const p=project();if(!p)return;$('#projectTitle').textContent=p.title||'Untitled';$('#projectSizeLabel').textContent=`${p.width} × ${p.height}`;const layer=$('#objectsLayer');layer.innerHTML=p.objects.map((o,i)=>{o.z=i+1;return objectHTML(o)}).join('');hydrateMedia(layer);applyStage();renderPanel(state().activeTool||'add')}
  function selectObject(id,additive=false){const p=project();if(!p)return;if(additive)state().selectedIds=state().selectedIds.includes(id)?state().selectedIds.filter(x=>x!==id):[...state().selectedIds,id];else state().selectedIds=[id];renderEditor()}
  function addObject(o){const p=project();if(!p)return;const base={id:uid(o.type),x:p.width*.18,y:p.height*.25,w:p.width*.64,h:180,rotation:0,opacity:1,hidden:false,locked:false,...o};commit(pp=>{pp.objects.push(base);state().selectedIds=[base.id]});return base}
  function deleteSelected(){if(!state().selectedIds.length)return;commit(p=>{p.objects=p.objects.filter(o=>!state().selectedIds.includes(o.id));state().selectedIds=[]})}
  function duplicateSelected(){const o=selected();if(!o)return;const c=clone(o);c.id=uid(o.type);c.x+=35;c.y+=35;c.name=`${objName(o)} copy`;commit(p=>{p.objects.push(c);state().selectedIds=[c.id]})}
  function rotate90(){const o=selected();if(!o)return;commit(p=>{const t=p.objects.find(x=>x.id===o.id);t.rotation=((t.rotation||0)+90)%360})}
  function moveLayer(dir){const id=state().selectedIds[0];if(!id)return;commit(p=>{const i=p.objects.findIndex(o=>o.id===id),j=clamp(i+dir,0,p.objects.length-1);if(i!==j)[p.objects[i],p.objects[j]]=[p.objects[j],p.objects[i]]})}
  function toggleLock(){const o=selected();if(!o)return;commit(p=>{const t=p.objects.find(x=>x.id===o.id);t.locked=!t.locked})}
  function toggleHidden(id){commit(p=>{const t=p.objects.find(x=>x.id===id);if(t)t.hidden=!t.hidden})}
  function updateSelected(patch){const o=selected();if(!o)return;commit(p=>Object.assign(p.objects.find(x=>x.id===o.id),patch))}
  function syncObject(id){const p=project(),o=p?.objects.find(x=>x.id===id),el=o?$(`[data-object-id="${CSS.escape(id)}"]`):null;if(!o||!el)return;el.style.width=`${o.w}px`;el.style.height=`${o.h}px`;el.style.transform=transform(o);el.style.opacity=o.opacity??1;const text=el.querySelector('.text-content');if(text){text.style.fontSize=`${o.fontSize||60}px`;text.style.lineHeight=o.lineHeight||1.1;text.style.letterSpacing=`${o.letterSpacing||0}px`;text.style.color=o.color||'#543944';text.style.fontFamily=o.fontFamily||'Georgia, serif'}const media=el.querySelector('.media-content img,.media-content video');if(media){media.style.transform=`translate(${o.mediaX||0}%,${o.mediaY||0}%) scale(${o.mediaScale||1})`;media.style.filter=filter(o);media.style.opacity=o.mediaOpacity??1;const wrap=el.querySelector('.media-content');if(wrap)wrap.style.borderRadius=`${o.radius||0}px`}const shape=el.querySelector('.shape-content');if(shape){shape.style.background=o.color||'#f7bfd0';shape.style.borderRadius=o.shape==='circle'?'50%':`${o.radius||24}px`}const sticker=el.querySelector('.sticker-content');if(sticker)sticker.style.fontSize=`${o.fontSize||Math.min(o.w,o.h)*.8}px`}
  function stagePoint(e){const r=$('#designStage').getBoundingClientRect(),z=state().zoom||1;return{x:(e.clientX-r.left)/z,y:(e.clientY-r.top)/z}}
  function snapped(o,x,y){const p=project();if(!p||!settings().snap)return{x,y,guide:false};let guide=false;const th=20,cx=x+o.w/2,cy=y+o.h/2;if(Math.abs(cx-p.width/2)<th){x=p.width/2-o.w/2;guide=true}if(Math.abs(cy-p.height/2)<th){y=p.height/2-o.h/2;guide=true}if(Math.abs(x)<th)x=0;if(Math.abs(y)<th)y=0;if(Math.abs(x+o.w-p.width)<th)x=p.width-o.w;if(Math.abs(y+o.h-p.height)<th)y=p.height-o.h;return{x,y,guide}}
  function contain(o,x,y){const p=project();if(!p||!settings().contain)return{x,y};return{x:clamp(x,0,Math.max(0,p.width-o.w)),y:clamp(y,0,Math.max(0,p.height-o.h))}}
  function pointerDown(e){const stage=$('#designStage');if(!stage.contains(e.target))return;activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state().drawMode){beginDraw(e);return}const el=e.target.closest('.canvas-object');if(!el){state().selectedIds=[];renderEditor();return}const id=el.dataset.objectId,o=project()?.objects.find(x=>x.id===id);if(!o)return;if(!state().selectedIds.includes(id)){state().selectedIds=e.shiftKey||e.metaKey?[...state().selectedIds,id]:[id];$$('.canvas-object').forEach(n=>n.classList.toggle('selected',state().selectedIds.includes(n.dataset.objectId)));renderPanel(state().activeTool||'add')}if(o.locked)return;const handle=e.target.closest('[data-handle]')?.dataset.handle;if(handle==='delete'){deleteSelected();return}if(activePointers.size===2){beginGesture();e.preventDefault();return}interaction={id,mode:handle||'move',start:stagePoint(e),orig:clone(o)};el.setPointerCapture?.(e.pointerId);e.preventDefault()}
  function pointerMove(e){if(activePointers.has(e.pointerId))activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state().drawMode&&drawSession){moveDraw(e);return}if(activePointers.size>=2&&state().selectedIds.length){if(!gesture)beginGesture();moveGesture();return}if(!interaction)return;const p=project(),o=p?.objects.find(x=>x.id===interaction.id);if(!o)return;const pt=stagePoint(e),dx=pt.x-interaction.start.x,dy=pt.y-interaction.start.y;if(interaction.mode==='move'){let a=snapped(o,interaction.orig.x+dx,interaction.orig.y+dy);a={...a,...contain(o,a.x,a.y)};o.x=a.x;o.y=a.y;$('#selectionGuides').classList.toggle('show',a.guide)}else if(interaction.mode==='resize'){o.w=clamp(interaction.orig.w+dx,40,p.width*2);o.h=clamp(interaction.orig.h+dy,40,p.height*2);if(settings().contain){o.w=Math.min(o.w,p.width-o.x);o.h=Math.min(o.h,p.height-o.y)}}else if(interaction.mode==='rotate'){const c={x:interaction.orig.x+interaction.orig.w/2,y:interaction.orig.y+interaction.orig.h/2},a0=Math.atan2(interaction.start.y-c.y,interaction.start.x-c.x),a1=Math.atan2(pt.y-c.y,pt.x-c.x);o.rotation=interaction.orig.rotation+(a1-a0)*180/Math.PI}syncObject(o.id)}
  function pointerUp(e){activePointers.delete(e.pointerId);if(state().drawMode&&drawSession){endDraw();return}if(gesture&&activePointers.size<2){gesture=null;finalizeInteraction();return}if(interaction){interaction=null;finalizeInteraction()}}
  function finalizeInteraction(){const p=project();if(!p)return;$('#selectionGuides').classList.remove('show');p.updatedAt=new Date().toISOString();save();pushHistory();renderPanel(state().activeTool||'add')}
  function beginGesture(){const pts=[...activePointers.values()];if(pts.length<2)return;const o=selected();if(!o||o.locked)return;gesture={id:o.id,d:Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y),a:Math.atan2(pts[1].y-pts[0].y,pts[1].x-pts[0].x),orig:clone(o)};interaction=null}
  function moveGesture(){if(!gesture)return;const pts=[...activePointers.values()];if(pts.length<2)return;const p=project(),o=p?.objects.find(x=>x.id===gesture.id);if(!o)return;const d=Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y),a=Math.atan2(pts[1].y-pts[0].y,pts[1].x-pts[0].x),ratio=d/Math.max(1,gesture.d);o.w=clamp(gesture.orig.w*ratio,40,p.width*2);o.h=clamp(gesture.orig.h*ratio,40,p.height*2);o.rotation=gesture.orig.rotation+(a-gesture.a)*180/Math.PI;syncObject(o.id)}
  function beginDraw(e){const pt=stagePoint(e);drawSession={points:[pt],color:state().drawColor||'#d96b8e',width:state().drawWidth||14};const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='drawPreview';svg.classList.add('draw-preview');svg.setAttribute('viewBox',`0 0 ${project().width} ${project().height}`);svg.innerHTML=`<polyline fill="none" stroke="${drawSession.color}" stroke-width="${drawSession.width}" stroke-linecap="round" stroke-linejoin="round"/>`;$('#designStage').append(svg);e.preventDefault()}
  function moveDraw(e){const pt=stagePoint(e);drawSession.points.push(pt);const line=$('#drawPreview polyline');if(line)line.setAttribute('points',drawSession.points.map(p=>`${p.x},${p.y}`).join(' '))}
  function endDraw(){const d=drawSession;drawSession=null;$('#drawPreview')?.remove();if(!d||d.points.length<2)return;const xs=d.points.map(p=>p.x),ys=d.points.map(p=>p.y),minX=Math.max(0,Math.min(...xs)-d.width),minY=Math.max(0,Math.min(...ys)-d.width),maxX=Math.max(...xs)+d.width,maxY=Math.max(...ys)+d.width;addObject({type:'drawing',x:minX,y:minY,w:Math.max(40,maxX-minX),h:Math.max(40,maxY-minY),points:d.points.map(p=>({x:p.x-minX,y:p.y-minY})),color:d.color,strokeWidth:d.width,name:'Drawing'})}
  function panelHeader(title,subtitle=''){return`<div class="panel-title"><strong>${title}</strong>${subtitle?`<small>${subtitle}</small>`:''}</div>`}
  function quickActions(){const o=selected();if(!o)return'';return`<div class="quick-actions"><button data-editor-action="duplicate">Duplicate</button><button data-editor-action="rotate90">Rotate 90°</button><button data-editor-action="forward">Forward</button><button data-editor-action="backward">Backward</button><button data-editor-action="lock">${o.locked?'Unlock':'Lock'}</button><button class="danger" data-editor-action="delete">Delete</button></div>`}
  function layerIcon(o){return o.type==='text'?'Aa':o.type==='image'?'▧':o.type==='video'?'▶':o.type==='sticker'?'✦':o.type==='shape'?'○':o.type==='frame'?'▣':o.type==='drawing'?'⌁':'◇'}
  function fontOptions(current){const base=[['ui-rounded, system-ui','Rounded'],['system-ui','Clean'],['Georgia, serif','Editorial'],['ui-monospace, monospace','Typewriter'],['cursive','Handwriting'],['Arial Black, system-ui','Bold']],custom=W.Store.fonts().map(f=>[f.family,f.name]);return[...base,...custom].map(([v,n])=>`<option value="${v}" ${current===v?'selected':''}>${escapeHtml(n)}</option>`).join('')}
  function renderPanel(tool){const box=$('#panelContent');if(!box)return;state().activeTool=tool;$$('#editorToolbar button').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));const o=selected();let h='<div class="panel-section">';if(tool==='add')h+=panelHeader('Add to your design')+`<div class="tool-grid"><button class="tool-button" data-editor-action="add-text"><span>Aa</span>Text</button><button class="tool-button" data-editor-action="open-media"><span>▧</span>Photo / Video</button><button class="tool-button" data-editor-action="add-shape"><span>○</span>Shape</button><button class="tool-button" data-editor-action="add-frame"><span>▣</span>Photo frame</button></div>`+(o?quickActions():'');if(tool==='text'){if(!o||o.type!=='text')h+=panelHeader('Text')+`<div class="panel-row">${W.TEXT_PRESETS.map(x=>`<button class="panel-chip" data-add-text="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('')}</div><button class="tool-button" data-editor-action="add-text"><span>＋</span>Add custom text</button>`;else h+=panelHeader('Edit text',objName(o))+`<div class="panel-fields"><div class="panel-field full"><label>Text</label><textarea data-prop="text">${escapeHtml(o.text||'')}</textarea></div><div class="panel-field"><label>Font</label><select data-prop="fontFamily">${fontOptions(o.fontFamily)}</select></div><div class="panel-field"><label>Size</label><input data-prop="fontSize" type="number" min="12" max="500" value="${o.fontSize||60}"></div><div class="panel-field"><label>Color</label><input data-prop="color" type="color" value="${o.color||'#543944'}"></div><div class="panel-field"><label>Weight</label><select data-prop="fontWeight"><option ${o.fontWeight==400?'selected':''}>400</option><option ${o.fontWeight==600?'selected':''}>600</option><option ${o.fontWeight==700?'selected':''}>700</option><option ${o.fontWeight==900?'selected':''}>900</option></select></div><div class="panel-field"><label>Alignment</label><select data-prop="align"><option value="left" ${o.align==='left'?'selected':''}>Left</option><option value="center" ${o.align==='center'?'selected':''}>Center</option><option value="right" ${o.align==='right'?'selected':''}>Right</option></select></div><div class="panel-field"><label>Letter spacing</label><input data-prop="letterSpacing" type="range" min="-5" max="30" value="${o.letterSpacing||0}"></div><div class="panel-field"><label>Line height</label><input data-prop="lineHeight" type="range" min="0.8" max="2" step="0.05" value="${o.lineHeight||1.1}"></div></div><div class="panel-row">${['none','outline','shadow','glow','offset','highlight','sticker'].map(x=>`<button class="panel-chip ${o.effect===x?'active':''}" data-text-effect="${x}">${x}</button>`).join('')}</div>${quickActions()}`}
  if(tool==='media'){if(!o||!['image','video','frame'].includes(o.type))h+=panelHeader('Photos & video')+`<div class="tool-grid"><button class="tool-button" data-editor-action="open-media"><span>＋</span>Add media</button><button class="tool-button" data-editor-action="add-frame"><span>▣</span>Add frame</button><button class="tool-button" data-editor-action="photo-dump"><span>🎞</span>Photo dump</button><button class="tool-button" data-editor-action="smart-layout"><span>✦</span>Smart layout</button></div>`;else if(o.type==='frame')h+=panelHeader('Empty photo frame')+`<button class="tool-button" data-editor-action="fill-frame"><span>＋</span>Choose photo</button>${quickActions()}`;else h+=panelHeader(o.type==='video'?'Video':'Photo')+`<div class="panel-fields"><div class="panel-field"><label>Fit</label><select data-prop="fit"><option value="cover" ${o.fit!=='contain'?'selected':''}>Fill frame</option><option value="contain" ${o.fit==='contain'?'selected':''}>Fit inside</option></select></div><div class="panel-field"><label>Corner radius</label><input data-prop="radius" type="range" min="0" max="120" value="${o.radius||0}"></div><div class="panel-field"><label>Zoom</label><input data-prop="mediaScale" type="range" min="1" max="3" step="0.05" value="${o.mediaScale||1}"></div><div class="panel-field"><label>Opacity</label><input data-prop="mediaOpacity" type="range" min="0.1" max="1" step="0.05" value="${o.mediaOpacity??1}"></div><div class="panel-field"><label>Brightness</label><input data-prop="brightness" type="range" min="40" max="160" value="${o.brightness??100}"></div><div class="panel-field"><label>Contrast</label><input data-prop="contrast" type="range" min="40" max="180" value="${o.contrast??100}"></div><div class="panel-field"><label>Saturation</label><input data-prop="saturation" type="range" min="0" max="220" value="${o.saturation??100}"></div><div class="panel-field"><label>Fade</label><input data-prop="sepia" type="range" min="0" max="70" value="${o.sepia??0}"></div></div><div class="panel-row">${['clean','soft pink','warm film','cool film','digicam','B&W','faded'].map(x=>`<button class="panel-chip" data-filter-preset="${x}">${x}</button>`).join('')}</div>${quickActions()}`}
  if(tool==='stickers')h+=panelHeader('Stickers & little details')+`<div class="sticker-grid">${W.STICKERS.map(x=>`<button class="sticker-button" data-add-sticker="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('')}</div>`+(o?.type==='sticker'?quickActions():'');if(tool==='draw')h+=panelHeader('Draw on your story')+`<div class="drawing-status">${state().drawMode?'Drawing is ON — use one finger on the canvas':'Choose a brush, then draw directly on the canvas'}</div><div class="panel-fields"><div class="panel-field"><label>Color</label><input id="drawColor" type="color" value="${state().drawColor||'#d96b8e'}"></div><div class="panel-field"><label>Width</label><input id="drawWidth" type="range" min="3" max="60" value="${state().drawWidth||14}"></div></div><div class="quick-actions"><button data-editor-action="toggle-draw">${state().drawMode?'Stop drawing':'Start drawing'}</button></div>`;if(tool==='style'){if(!o)h+=panelHeader('Canvas style')+`<div class="panel-field"><label>Background</label><input id="canvasBackground" type="color" value="${project()?.background||'#fff7fa'}"></div><div class="color-swatch-row">${['#fff7fa','#f8c3d8','#fff5e8','#f3e9ff','#e6f0ff','#222025','#ffffff'].map(c=>`<button class="color-swatch" data-canvas-color="${c}" style="background:${c}"></button>`).join('')}</div>`;else h+=panelHeader('Layer style',objName(o))+`<div class="panel-fields"><div class="panel-field"><label>Opacity</label><input data-prop="opacity" type="range" min=".1" max="1" step=".05" value="${o.opacity??1}"></div>${o.type==='shape'?`<div class="panel-field"><label>Color</label><input data-prop="color" type="color" value="${o.color||'#f7bfd0'}"></div><div class="panel-field"><label>Radius</label><input data-prop="radius" type="range" min="0" max="160" value="${o.radius||20}"></div>`:''}</div>${quickActions()}`}
  if(tool==='layers')h+=panelHeader('Layers',`${project()?.objects.length||0} layers`)+`<div class="layer-list">${[...(project()?.objects||[])].reverse().map(o=>`<div class="layer-row ${state().selectedIds.includes(o.id)?'selected':''}"><span class="layer-icon">${layerIcon(o)}</span><button class="layer-copy" data-select-layer="${o.id}"><strong>${escapeHtml(objName(o))}</strong><small>${o.type}</small></button><div class="layer-controls"><button data-layer-action="hide" data-id="${o.id}">${o.hidden?'◉':'○'}</button><button data-layer-action="lock" data-id="${o.id}">${o.locked?'🔒':'🔓'}</button></div></div>`).join('')}</div>`;if(tool==='more')h+=panelHeader('More tools')+`<div class="tool-grid"><button class="tool-button" data-editor-action="resize-project"><span>↔</span>Resize</button><button class="tool-button" data-editor-action="remix"><span>⤨</span>Remix</button><button class="tool-button" data-editor-action="save-template"><span>♡</span>Save template</button><button class="tool-button" data-editor-action="rename-project"><span>✎</span>Rename</button><button class="tool-button" data-editor-action="toggle-guides"><span>⌗</span>Safe zones</button><button class="tool-button" data-editor-action="toggle-grid"><span>▦</span>Grid</button><button class="tool-button" data-editor-action="smart-layout"><span>✦</span>Smart layout</button><button class="tool-button" data-editor-action="select-all"><span>✓</span>Select all</button></div>`+(o?quickActions():'');box.innerHTML=h+'</div>'}
  function propInput(e,live=false){const el=e.target.closest('[data-prop]');if(!el)return;let v=el.value;if(el.type==='range'||el.type==='number')v=Number(v);if(live){const o=selected();if(!o)return;o[el.dataset.prop]=v;syncObject(o.id);return}updateSelected({[el.dataset.prop]:v})}
  function filterPreset(name){const m={clean:{brightness:100,contrast:100,saturation:100,sepia:0},'soft pink':{brightness:108,contrast:92,saturation:90,sepia:10},'warm film':{brightness:102,contrast:108,saturation:92,sepia:22},'cool film':{brightness:104,contrast:103,saturation:82,sepia:0},digicam:{brightness:112,contrast:125,saturation:125,sepia:0},'B&W':{brightness:103,contrast:115,saturation:0,sepia:0},faded:{brightness:108,contrast:82,saturation:75,sepia:18}};updateSelected(m[name]||m.clean)}
  function smartLayout(){const p=project();if(!p)return;const media=p.objects.filter(o=>['image','video','frame'].includes(o.type)&&!o.hidden);if(!media.length){W.toast?.('Add photos or frames first');return}const gap=40,cols=media.length===1?1:media.length<=4?2:3,rows=Math.ceil(media.length/cols),cellW=(p.width-gap*(cols+1))/cols,top=p.height*.16,available=p.height*.68,cellH=(available-gap*(rows-1))/rows;commit(()=>media.forEach((o,i)=>{o.x=gap+(i%cols)*(cellW+gap);o.y=top+Math.floor(i/cols)*(cellH+gap);o.w=cellW;o.h=cellH;o.rotation=0}));W.toast?.('Smart layout applied')}
  function remix(){const p=project();if(!p)return;commit(()=>p.objects.forEach((o,i)=>{if(o.locked)return;o.rotation=(Math.random()-.5)*10;if(i%2===0){o.x=clamp(o.x+(Math.random()-.5)*80,0,Math.max(0,p.width-o.w));o.y=clamp(o.y+(Math.random()-.5)*80,0,Math.max(0,p.height-o.h))}}));W.toast?.('Layout remixed ✦')}
  function selectAll(){const p=project();if(!p)return;state().selectedIds=p.objects.filter(o=>!o.hidden).map(o=>o.id);renderEditor()}
  async function imageDims(file,p){return new Promise(resolve=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{const ratio=im.naturalWidth/im.naturalHeight;URL.revokeObjectURL(u);let w=p.width*.72,h=w/ratio;if(h>p.height*.65){h=p.height*.65;w=h*ratio}resolve({w,h})};im.onerror=()=>{URL.revokeObjectURL(u);resolve({w:p.width*.72,h:p.width*.72})};im.src=u})}
  async function mediaFiles(files,{replaceId=null}={}){const p=project();if(!p||!files?.length)return;for(const file of files){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))continue;const id=await W.MediaDB.put(file,{name:file.name,type:file.type});let dims=file.type.startsWith('image/')?await imageDims(file,p):{w:p.width*.78,h:p.width*.56};if(replaceId){commit(pp=>{const o=pp.objects.find(x=>x.id===replaceId);if(o)Object.assign(o,{type:file.type.startsWith('video/')?'video':'image',mediaId:id,fit:'cover',mediaScale:1,mediaX:0,mediaY:0,brightness:100,contrast:100,saturation:100,sepia:0})});replaceId=null}else addObject({type:file.type.startsWith('video/')?'video':'image',mediaId:id,w:dims.w,h:dims.h,x:(p.width-dims.w)/2,y:(p.height-dims.h)/2,fit:'cover',radius:20,name:file.name})}}
  function applyTemplate(tpl){const fmt=W.FORMATS[tpl.format]||W.FORMATS.portrait,id=W.createProject?.({format:fmt.id,title:tpl.name,background:tpl.background,objects:tpl.objects.map(o=>({...clone(o),id:uid(o.type)}))});if(id)openProject(id)}
  function openProject(id){state().currentProjectId=id;state().selectedIds=[];state().history=[];state().future=[];state().zoom=0;state().drawMode=false;W.route?.('editor');requestAnimationFrame(()=>{state().zoom=fitZoom();renderEditor();pushHistory()})}
  function undo(){const p=project(),h=state().history;if(!p||h.length<2)return;state().future.push(h.pop());const snap=JSON.parse(h[h.length-1]);p.background=snap.background;p.objects=snap.objects;save();renderEditor()}
  function redo(){const p=project(),f=state().future;if(!p||!f.length)return;const raw=f.pop();state().history.push(raw);const snap=JSON.parse(raw);p.background=snap.background;p.objects=snap.objects;save();renderEditor()}
  function panelClick(e){const action=e.target.closest('[data-editor-action]')?.dataset.editorAction,addText=e.target.closest('[data-add-text]')?.dataset.addText,addSticker=e.target.closest('[data-add-sticker]')?.dataset.addSticker,effect=e.target.closest('[data-text-effect]')?.dataset.textEffect,preset=e.target.closest('[data-filter-preset]')?.dataset.filterPreset,color=e.target.closest('[data-canvas-color]')?.dataset.canvasColor,select=e.target.closest('[data-select-layer]')?.dataset.selectLayer,layerAction=e.target.closest('[data-layer-action]');if(addText!==undefined)addObject({type:'text',text:addText||'Your text',h:150,fontFamily:state().settings.defaultFont||'ui-rounded, system-ui',fontSize:64,fontWeight:600,color:state().settings.defaultText||'#543944',lineHeight:1.1,align:'left',effect:'none'});if(addSticker)addObject({type:'sticker',value:addSticker,w:150,h:150,fontSize:120});if(effect)updateSelected({effect});if(preset)filterPreset(preset);if(color)commit(p=>p.background=color);if(select)selectObject(select);if(layerAction){const id=layerAction.dataset.id;if(layerAction.dataset.layerAction==='hide')toggleHidden(id);else{selectObject(id);toggleLock()}return}if(!action)return;if(action==='add-text')addObject({type:'text',text:'Your text',h:160,fontFamily:state().settings.defaultFont||'ui-rounded, system-ui',fontSize:68,fontWeight:600,color:state().settings.defaultText||'#543944',lineHeight:1.1,align:'left',effect:'none'});if(action==='open-media'){$('#mediaInput').dataset.mode='editor';$('#mediaInput').click()}if(action==='add-shape')addObject({type:'shape',w:360,h:260,color:'#f7bfd0',radius:36});if(action==='add-frame')addObject({type:'frame',w:520,h:600,radius:28});if(action==='fill-frame'){const o=selected();if(o){$('#mediaInput').dataset.mode='replace';$('#mediaInput').dataset.replaceId=o.id;$('#mediaInput').click()}}if(action==='duplicate')duplicateSelected();if(action==='rotate90')rotate90();if(action==='forward')moveLayer(1);if(action==='backward')moveLayer(-1);if(action==='lock')toggleLock();if(action==='delete')deleteSelected();if(action==='toggle-draw'){state().drawMode=!state().drawMode;$('#editorView').classList.toggle('draw-mode',state().drawMode);renderPanel('draw')}if(action==='photo-dump')W.startPhotoDump?.();if(action==='smart-layout')smartLayout();if(action==='resize-project')W.openResizeModal?.();if(action==='remix')remix();if(action==='save-template')W.saveCurrentAsTemplate?.();if(action==='rename-project')W.openRenameModal?.();if(action==='toggle-guides'){state().settings.safeZones=!state().settings.safeZones;W.Store.saveSettings(state().settings);applyStage();renderPanel('more')}if(action==='toggle-grid'){state().settings.grid=!state().settings.grid;W.Store.saveSettings(state().settings);applyStage();renderPanel('more')}if(action==='select-all')selectAll()}
  function bind(){const stage=$('#designStage');stage.addEventListener('pointerdown',pointerDown);stage.addEventListener('pointermove',pointerMove);stage.addEventListener('pointerup',pointerUp);stage.addEventListener('pointercancel',pointerUp);$('#editorToolbar').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)renderPanel(b.dataset.tool)});$('#panelContent').addEventListener('change',e=>propInput(e,false));$('#panelContent').addEventListener('input',e=>{if(e.target.matches('input[type=range][data-prop]'))propInput(e,true);if(e.target.id==='drawColor')state().drawColor=e.target.value;if(e.target.id==='drawWidth')state().drawWidth=Number(e.target.value);if(e.target.id==='canvasBackground')commit(p=>p.background=e.target.value)});$('#panelContent').addEventListener('click',panelClick);$('#undoButton').addEventListener('click',undo);$('#redoButton').addEventListener('click',redo);$('#exitEditorButton').addEventListener('click',()=>W.route?.('projects'));$('#projectTitleButton').addEventListener('click',()=>W.openRenameModal?.());$('#editorWorkspace').addEventListener('click',e=>{const a=e.target.closest('[data-canvas-action]');if(!a)return;const action=a.dataset.canvasAction;if(action==='zoom-in'){state().zoom=clamp((state().zoom||fitZoom())+.05,.12,1);applyStage()}if(action==='zoom-out'){state().zoom=clamp((state().zoom||fitZoom())-.05,.12,1);applyStage()}if(action==='toggle-guides'){state().settings.safeZones=!state().settings.safeZones;W.Store.saveSettings(state().settings);applyStage()}});window.addEventListener('resize',()=>{if(state()?.currentRoute==='editor'&&!interaction&&!gesture){state().zoom=fitZoom();applyStage()}},{passive:true})}
  W.Editor={bind,render:renderEditor,renderPanel,openProject,applyTemplate,addObject,mediaFiles,smartLayout,remix,undo,redo,selectObject,deleteSelected,selected,project,fitZoom};
})();
